#pragma once

// --- precompiled header ----------------
#include "pch.h"
// ---------------------------------------

#include "core/core.h"
#include "core/io.h"
#include "core/maths.h"
#include "core/application.h"
#include "asset/asset_manager.h"
#include "core/layer.h"
#include "core/layer_stack.h"
#include "core/window.h"
#include "core/input.h"
#include "core/timer.h"
#include "core/keycodes.h"

#include "event/event.h"
#include "event/key_event.h"
#include "event/mouse_event.h"
#include "event/application_event.h"

#include "scene/scene.h"
#include "scene/entity.h"
#include "scene/animation_system.h"
#include "scene/component/base.h"
#include "scene/component/camera.h"
#include "scene/component/mesh.h"
#include "scene/component/sprite.h"
#include "scene/component/animation.h"

#include "render/global.h"
#include "render/graphics_context.h"
#include "render/render_pass.h"
#include "render/render_graph.h"
#include "render/resource.h"
#include "render/pipeline.h"
#include "render/buffer.h"
#include "render/shader.h"
#include "render/image.h"
#include "render/vertex_array.h"
#include "render/framebuffer.h"
#include "render/renderer/renderer_2d.h"
#include "render/renderer/renderer_forward.h"

#include "animation/animation.h"
#include "animation/skeleton.h"

#include "util/instrumentor.h"
#include "util/random_utils.h"
#include "util/string_utils.h"
#include "util/thread_pool.h"

#include "asset/asset.h"
#include "asset/binary_file.h"
#include "asset/texture.h"
#include "asset/material.h"
#include "asset/mesh.h"
#include "asset/importer/importer.h"
#include "asset/importer/gltf_importer.h"
#include "asset/importer/texture_importer.h"
#include "asset/importer/obj_importer.h"
