#pragma once

// --- precompiled header ----------------
#include "pch.h"
// ---------------------------------------

#include "core/core.h"
#include "core/io.h"
#include "core/maths.h"
#include "core/application.h"
#include "asset/asset_manager.h"
#include "core/layer.h"
#include "core/layer_stack.h"
#include "core/window.h"
#include "core/input.h"
#include "core/timer.h"
#include "core/keycodes.h"

#include "event/event.h"
#include "event/key_event.h"
#include "event/mouse_event.h"
#include "event/application_event.h"

#include "scene/scene.h"
#include "scene/entity.h"
#include "scene/component/base.h"
#include "scene/component/camera.h"
#include "scene/component/mesh.h"
#include "scene/component/sprite.h"

#include "render/graphics_context.h"
#include "asset/mesh.h"
#include "asset/material.h"
#include "render/render_pass.h"
#include "render/buffer.h"
#include "render/shader.h"
#include "render/image.h"
#include "render/vertex_array.h"
#include "render/framebuffer.h"
#include "render/renderer/renderer_2d.h"
#include "render/renderer/renderer_forward.h"

#include "util/instrumentor.h"
#include "util/random_utils.h"
#include "util/string_utils.h"
#include "util/thread_pool.h"

#include "asset/serializer/serializer.h"
#include "asset/serializer/binary_file.h"
#include "asset/serializer/scene_serializer.h"
#include "asset/serializer/mesh_serializer.h"
#include "asset/serializer/image_serializer.h"
#include "asset/importer/importer.h"
#include "asset/importer/gltf_importer.h"
#include "asset/importer/image_importer.h"
#include "asset/importer/obj_importer.h"
