# [AI-GENERATED] This file was generated by an AI agent.
"""asset_checker_core -- asset validation engine for z1engine content roots.

Mirrors AssetManager::scan_content()/resolve_guid() semantics: every asset
reference (guid or path string) must resolve to a registered asset. Pure
stdlib; shared by the GUI and the headless CLI.
"""

import argparse
import json
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

UUID_RE = re.compile(
	r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)

# render/data_types.h enum order: Sampler2D=12, Sampler2DArray=13, SamplerCube=14
SAMPLER_TYPES = {12, 13, 14}

DEFAULT_ROOTS = [
	("", "content"),
	("engine", "engine/content"),
]

# YAML key paths (relative to the asset root) where a string is an asset
# reference. "*" matches one segment of any kind (list index or map key).
REF_PATTERNS = [
	("shader",),
	("material",),
	("primitives", "*", "material"),
	("variables", "*", "value"),
	("overrides", "*", "value"),
	("entities", "*", "static_mesh", "guid"),
	("entities", "*", "skeletal_mesh", "guid"),
	("entities", "*", "skeletal_mesh", "skeleton"),
	("entities", "*", "static_mesh", "override_materials", "*"),
	("entities", "*", "skeletal_mesh", "override_materials", "*"),
	("entities", "*", "sprite", "texture"),
	("entities", "*", "particle", "texture"),
	("entities", "*", "sky_light", "texture"),
	("entities", "*", "animation", "animation_asset"),
]


@dataclass
class Issue:
	severity: str
	file: str
	location: str
	message: str


@dataclass
class AssetRef:
	value: str
	kind: str
	location: str
	target: str = None


@dataclass
class AssetInfo:
	root_name: str
	kind: str
	file: str
	guid: str
	type: str
	path: str
	refs: list = field(default_factory=list)


@dataclass
class Report:
	roots: list = field(default_factory=list)
	assets: list = field(default_factory=list)
	issues: list = field(default_factory=list)
	counts: dict = field(default_factory=dict)
	elapsed: float = 0.0


# ---------------------------------------------------------------------------
# Minimal YAML subset parser (no third-party deps)
# ---------------------------------------------------------------------------
class YamlParseError(Exception):
	pass


def _strip_comment(line):
	quote = None
	for i, ch in enumerate(line):
		if quote:
			if ch == quote:
				quote = None
		elif ch in "'\"":
			quote = ch
		elif ch == "#" and (i == 0 or line[i - 1] in " \t"):
			return line[:i]
	return line


def _unquote(token):
	if len(token) >= 2 and token[0] in "'\"" and token[-1] == token[0]:
		inner = token[1:-1]
		if token[0] == "'":
			return inner.replace("''", "'")
		return inner.replace('\\"', '"').replace("\\n", "\n")
	return token


def _parse_scalar(token):
	if token == "" or token == "~":
		return None
	if token.lower() == "null":
		return None
	if token.lower() == "true":
		return True
	if token.lower() == "false":
		return False
	if len(token) >= 2 and token[0] in "'\"" and token[-1] == token[0]:
		return _unquote(token)
	base = 16 if token.lower().startswith("0x") else 10
	try:
		return int(token, base)
	except ValueError:
		pass
	try:
		return float(token)
	except ValueError:
		pass
	return token


def _split_key(text):
	"""Return (key, rest) for a 'key: value' line, or (None, None)."""
	quote = None
	depth = 0
	i = 0
	while i < len(text):
		ch = text[i]
		if quote:
			if ch == quote:
				quote = None
			i += 1
			continue
		if ch in "'\"":
			quote = ch
			i += 1
			continue
		if ch in "[{":
			depth += 1
			i += 1
			continue
		if ch in "]}":
			depth -= 1
			i += 1
			continue
		if ch == ":" and depth == 0 and (i + 1 == len(text) or text[i + 1] in " \t"):
			return _unquote(text[:i].strip()), text[i + 1:].lstrip()
		i += 1
	return None, None


def _flow_balanced(text):
	depth = 0
	quote = None
	i = 0
	while i < len(text):
		ch = text[i]
		if quote:
			if ch == quote:
				quote = None
			i += 1
			continue
		if ch in "'\"":
			quote = ch
		elif ch in "[{":
			depth += 1
		elif ch in "]}":
			depth -= 1
		i += 1
	return depth <= 0


def _parse_flow(text, i):
	open_ch = text[i]
	close_ch = "]" if open_ch == "[" else "}"
	is_map = open_ch == "{"
	i += 1
	result = [] if not is_map else {}
	while True:
		while i < len(text) and text[i] in " \t\r\n,":
			i += 1
		if i >= len(text):
			raise YamlParseError("unterminated flow collection")
		if text[i] == close_ch:
			return result, i + 1
		key = None
		if is_map:
			key, i = _flow_scalar(text, i)
			while i < len(text) and text[i] in " \t\r\n":
				i += 1
			if i >= len(text) or text[i] != ":":
				raise YamlParseError("expected ':' in flow mapping")
			i += 1
			while i < len(text) and text[i] in " \t\r\n":
				i += 1
		if i < len(text) and text[i] in "[{":
			value, i = _parse_flow(text, i)
		else:
			value, i = _flow_scalar(text, i)
		if is_map:
			result[key] = value
		else:
			result.append(value)


def _flow_scalar(text, i):
	quote = None
	start = i
	while i < len(text):
		ch = text[i]
		if quote:
			if ch == "\\" and quote == '"' and i + 1 < len(text):
				i += 2
				continue
			if ch == quote:
				quote = None
			i += 1
			continue
		if ch in "'\"":
			quote = ch
			i += 1
			continue
		if ch in ",]}":
			break
		i += 1
	return _parse_scalar(text[start:i].strip()), i


def _parse_inline(lines, i, rest, indent):
	"""Parse the value that follows a 'key:' at line i. Returns (value, next_i)."""
	if rest == "":
		j = i + 1
		while j < len(lines) and lines[j][0] <= indent:
			j += 1
		if j >= len(lines):
			return None, i + 1
		value, j = _parse_block(lines, j, lines[j][0])
		return value, j
	if rest[0] in "[{":
		combined = rest
		j = i + 1
		while not _flow_balanced(combined) and j < len(lines):
			combined += "\n" + lines[j][1]
			j += 1
		if not _flow_balanced(combined):
			raise YamlParseError(f"unterminated flow collection near: {rest}")
		return _parse_flow(combined, 0)[0], j
	return _parse_scalar(rest), i + 1


def _parse_map(lines, i, indent):
	mapping = {}
	while i < len(lines):
		ind, text = lines[i]
		if ind < indent:
			break
		if ind > indent:
			raise YamlParseError(f"unexpected indentation near: {text}")
		if text == "-" or text.startswith("- "):
			break
		key, rest = _split_key(text)
		if key is None:
			raise YamlParseError(f"expected 'key: value' near: {text}")
		value, i = _parse_inline(lines, i, rest, indent)
		mapping[key] = value
	return mapping, i


def _parse_seq(lines, i, indent):
	seq = []
	while i < len(lines):
		ind, text = lines[i]
		if ind != indent:
			break
		if not (text == "-" or text.startswith("- ")):
			break
		rest = text[1:].lstrip()
		if rest == "":
			j = i + 1
			while j < len(lines) and lines[j][0] <= indent:
				j += 1
			if j >= len(lines):
				seq.append(None)
				i = j
			else:
				value, j = _parse_block(lines, j, lines[j][0])
				seq.append(value)
				i = j
			continue
		key, key_rest = _split_key(rest)
		if key is not None:
			item_indent = indent + 2
			item = {}
			value, i = _parse_inline(lines, i, key_rest, item_indent)
			item[key] = value
			while i < len(lines) and lines[i][0] == item_indent:
				nested_key, nested_rest = _split_key(lines[i][1])
				if nested_key is None:
					break
				value, i = _parse_inline(lines, i, nested_rest, item_indent)
				item[nested_key] = value
			seq.append(item)
			continue
		value, i = _parse_inline(lines, i, rest, indent)
		seq.append(value)
	return seq, i


def _parse_block(lines, i, indent):
	text = lines[i][1]
	if text == "-" or text.startswith("- "):
		return _parse_seq(lines, i, indent)
	if text and text[0] in "[{":
		combined = text
		j = i + 1
		while not _flow_balanced(combined) and j < len(lines):
			combined += "\n" + lines[j][1]
			j += 1
		if not _flow_balanced(combined):
			raise YamlParseError(f"unterminated flow collection near: {text}")
		return _parse_flow(combined, 0)[0], j
	return _parse_map(lines, i, indent)


def parse_yaml(text):
	lines = []
	for raw in text.splitlines():
		line = _strip_comment(raw)
		if not line.strip():
			continue
		indent = len(line) - len(line.lstrip(" \t"))
		lines.append((indent, line[indent:].rstrip()))
	if not lines:
		return None
	value, i = _parse_block(lines, 0, lines[0][0])
	if i < len(lines):
		raise YamlParseError(f"unparsed trailing content near: {lines[i][1]}")
	return value


# ---------------------------------------------------------------------------
# Registry + validation (mirrors AssetManager::scan_content / resolve_guid)
# ---------------------------------------------------------------------------
def repo_root_dir():
	return Path(__file__).resolve().parents[3]


def _display(root_name, rel):
	return rel if not root_name else f"{root_name}/{rel}"


def _internal_key(root_name, path_str):
	path_str = path_str.replace("\\", "/")
	if root_name:
		return f":{root_name}/{path_str}"
	return path_str


def _format_path(path):
	parts = []
	for segment in path:
		if isinstance(segment, int):
			parts.append(f"[{segment}]")
		else:
			if parts:
				parts.append(".")
			parts.append(str(segment))
	return "".join(parts)


def _matches_ref_pattern(segments):
	return any(
		len(segments) == len(pattern)
		and all(seg == "*" or seg == actual for seg, actual in zip(pattern, segments))
		for pattern in REF_PATTERNS
	)


def _collect_refs(value, path, parent, out):
	if isinstance(value, dict):
		for key, item in value.items():
			_collect_refs(item, path + [key], value, out)
	elif isinstance(value, list):
		for index, item in enumerate(value):
			_collect_refs(item, path + [index], None, out)
	elif isinstance(value, str) and value:
		if UUID_RE.match(value):
			out.append(AssetRef(value, "guid", _format_path(path)))
			return
		segments = tuple(path)
		if _matches_ref_pattern(segments):
			if segments[-1] == "value" and segments[-2] in ("variables", "overrides"):
				if not isinstance(parent, dict) or parent.get("type") not in SAMPLER_TYPES:
					return
			out.append(AssetRef(value, "path", _format_path(path)))


def _register_derived(report, rel, root_name, kind, guid_registry, path_registry):
	internal_key = _internal_key(root_name, rel)
	if internal_key in path_registry:
		return
	display = _display(root_name, rel)
	if rel in guid_registry:
		report.issues.append(Issue("error", display, "",
			f"duplicate guid '{rel}' (also used by {guid_registry[rel]})"))
		return
	guid_registry[rel] = display
	path_registry[internal_key] = rel
	report.assets.append(AssetInfo(root_name, kind, display, rel, kind, rel))


def _scan_yaml(report, file, rel, root_name, guid_registry, path_registry):
	display = _display(root_name, rel)
	try:
		text = file.read_text(encoding="utf-8", errors="replace")
	except OSError as exc:
		report.issues.append(Issue("error", display, "", f"failed to read file: {exc}"))
		return
	try:
		doc = parse_yaml(text)
	except YamlParseError as exc:
		report.issues.append(Issue("error", display, "", f"yaml parse error: {exc}"))
		return
	if not isinstance(doc, dict):
		report.issues.append(Issue("error", display, "", "document root is not a mapping"))
		return
	meta = doc.get("meta")
	if not isinstance(meta, dict):
		report.issues.append(Issue("error", display, "meta", "missing meta block"))
		return
	guid = meta.get("guid")
	type_name = meta.get("type")
	asset_path = meta.get("path")
	guid_str = guid if isinstance(guid, str) else ""
	type_str = type_name if isinstance(type_name, str) else ""
	path_str = asset_path if isinstance(asset_path, str) else ""
	ok = True
	if not guid_str.strip():
		report.issues.append(Issue("error", display, "meta.guid", "missing or empty guid"))
		ok = False
	if not type_str.strip():
		report.issues.append(Issue("error", display, "meta.type", "missing or empty type"))
	if not path_str.strip():
		report.issues.append(Issue("error", display, "meta.path", "missing or empty path"))
	if not ok or not guid_str.strip():
		return
	if guid_str in guid_registry:
		report.issues.append(Issue("error", display, "meta.guid",
			f"duplicate guid '{guid_str}' (also used by {guid_registry[guid_str]})"))
		return
	internal_key = _internal_key(root_name, path_str)
	if internal_key in path_registry:
		report.issues.append(Issue("warning", display, "meta.path",
			f"duplicate asset path '{path_str}' (already claimed by guid {path_registry[internal_key]})"))
	else:
		path_registry[internal_key] = guid_str
	guid_registry[guid_str] = display
	info = AssetInfo(root_name, "yaml", display, guid_str, type_str, path_str)
	for key, value in doc.items():
		if key == "meta":
			continue
		_collect_refs(value, [key], None, info.refs)
	report.assets.append(info)


def _resolve_ref_target(ref, guid_registry, path_registry, named_roots):
	"""Resolve a reference to the display key of its target asset (or None)."""
	ref = ref.replace("\\", "/")
	if ref in guid_registry:
		return guid_registry[ref]
	if ref in path_registry:
		guid = path_registry[ref]
		return guid_registry.get(guid, guid)
	for name in named_roots:
		key = f":{name}/{ref}"
		if key in path_registry:
			guid = path_registry[key]
			return guid_registry.get(guid, guid)
	return None


def check_assets(roots=None, base_dir=None):
	if roots is None:
		roots = list(DEFAULT_ROOTS)
	if base_dir is None:
		base_dir = repo_root_dir()
	start = time.time()
	report = Report()
	guid_registry = {}
	path_registry = {}
	root_paths = []
	seen = set()
	for name, path_str in roots:
		key = (name, path_str.replace("\\", "/"))
		if key in seen:
			continue
		seen.add(key)
		path = Path(path_str)
		if not path.is_absolute():
			path = base_dir / path
		root_paths.append((name, path))
	report.roots = [{"name": name, "path": str(path)} for name, path in root_paths]
	named_roots = [name for name, _ in root_paths if name]

	for name, path in root_paths:
		if not path.is_dir():
			report.issues.append(Issue("warning", name or "(default)", "",
				f"content root not found: {path}"))
			continue
		for entry in sorted(path.rglob("*"), key=lambda p: p.as_posix().lower()):
			if not entry.is_file():
				continue
			suffix = entry.suffix.lower()
			rel = entry.relative_to(path).as_posix()
			if suffix == ".yaml":
				_scan_yaml(report, entry, rel, name, guid_registry, path_registry)
			elif suffix == ".py":
				_register_derived(report, rel, name, "script", guid_registry, path_registry)
			elif suffix == ".glsl":
				stem_rel = Path(entry.parent / entry.stem).relative_to(path).as_posix()
				_register_derived(report, stem_rel, name, "shader", guid_registry, path_registry)

	for info in report.assets:
		for ref in info.refs:
			ref.target = _resolve_ref_target(ref.value, guid_registry, path_registry, named_roots)
			if ref.target is not None:
				continue
			if ref.kind == "guid":
				message = f"referenced guid not found: '{ref.value}'"
			else:
				message = f"unresolved asset reference: '{ref.value}'"
			report.issues.append(Issue("error", info.file, ref.location, message))

	errors = sum(1 for issue in report.issues if issue.severity == "error")
	warnings = sum(1 for issue in report.issues if issue.severity == "warning")
	refs = sum(len(a.refs) for a in report.assets)
	report.counts = {
		"assets": len(report.assets),
		"references": refs,
		"errors": errors,
		"warnings": warnings,
	}
	report.elapsed = time.time() - start
	return report


def report_to_dict(report):
	return {
		"roots": report.roots,
		"counts": report.counts,
		"elapsed": report.elapsed,
		"issues": [
			{"severity": i.severity, "file": i.file, "location": i.location, "message": i.message}
			for i in report.issues
		],
		"assets": [
			{
				"root": a.root_name, "file": a.file, "kind": a.kind,
				"guid": a.guid, "type": a.type, "path": a.path,
				"refs": [{"value": r.value, "kind": r.kind, "location": r.location,
					"target": r.target} for r in a.refs],
			}
			for a in report.assets
		],
	}


def parse_root_spec(spec):
	"""Parse a '[NAME:]PATH' root specification (e.g. 'engine:engine/content')."""
	value = spec.strip()
	if not value:
		return None
	if len(value) >= 2 and value[1] == ":" and value[0].isalpha():
		return ("", value)
	if ":" in value:
		name, _, rest = value.partition(":")
		if name and "/" not in name and "\\" not in name:
			return (name, rest)
	return ("", value)


def run_headless(roots, json_path):
	report = check_assets(roots)
	for issue in report.issues:
		tag = "FAIL" if issue.severity == "error" else "WARN"
		location = f" (at {issue.location})" if issue.location else ""
		print(f"[{tag}] {issue.file}: {issue.message}{location}")
	counts = report.counts
	print(f"[INFO] assets: {counts['assets']}, references: {counts['references']}, "
		f"errors: {counts['errors']}, warnings: {counts['warnings']} ({report.elapsed:.2f}s)")
	if json_path:
		with open(json_path, "w", encoding="utf-8", newline="\n") as f:
			json.dump(report_to_dict(report), f, indent="\t", ensure_ascii=False)
		print(f"[INFO] report written: {json_path}")
	if counts["errors"]:
		print(f"[FAIL] asset validation failed: {counts['errors']} error(s)")
		return 2
	print("[OK] all referenced guids are valid")
	return 0


def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="asset_checker",
		description="Validate all assets in the content roots: every referenced guid must resolve.",
	)
	parser.add_argument("--root", action="append", default=[], metavar="[NAME:]PATH",
		help="additional content root (repeatable); defaults: content, engine:engine/content")
	parser.add_argument("--json", metavar="FILE", help="write JSON report to FILE")
	args = parser.parse_args(argv)
	roots = list(DEFAULT_ROOTS)
	for spec in args.root:
		parsed = parse_root_spec(spec)
		if parsed:
			roots.append(parsed)
	return run_headless(roots, args.json)


if __name__ == "__main__":
	sys.exit(main())
