# [AI-GENERATED] This file was generated by an AI agent.
"""assetkit_gui -- unified asset tool: content browser, validation issues, import.

Merges the former asset_checker and importer tools into one application.
Left pane: content browser of every asset in the content roots.
Right pane: warnings/errors window plus a details pane with guid link
navigation. Run with --check for a headless validation pass.
"""

import argparse
import json
import re
import subprocess
import sys
import threading
from pathlib import Path
import tkinter as tk
from tkinter import font as tkfont
from tkinter import ttk, filedialog, messagebox

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
	sys.path.insert(0, str(SCRIPT_DIR))

import assetkit_core as core

UUID_PATTERN = r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
PREVIEW_LIMIT = 262144


class ToolTip:
	def __init__(self, widget):
		self.widget = widget
		self.tip_window = None

	def show(self, text, x, y):
		if self.tip_window or not text:
			return
		self.tip_window = tw = tk.Toplevel(self.widget)
		tw.wm_overrideredirect(True)
		tw.wm_geometry(f"+{x+15}+{y+10}")
		label = tk.Label(tw, text=text, justify=tk.LEFT,
			background="#ffffe0", relief=tk.SOLID, borderwidth=1,
			font=("tahoma", "8", "normal"))
		label.pack(ipadx=1)

	def hide(self):
		if self.tip_window:
			self.tip_window.destroy()
			self.tip_window = None


class AssetKitApp:
	def __init__(self, root, roots):
		self.root = root
		self.roots = roots
		self.base_dir = core.repo_root_dir()
		self.report = None
		self.running = False
		self._worker_result = None
		self.show_errors = tk.BooleanVar(value=True)
		self.show_warnings = tk.BooleanVar(value=True)
		self.browser_item_map = {}
		self.path_to_item = {}
		self.guid_to_path = {}
		self.asset_by_file = {}
		self.issue_by_file = {}
		self.ref_children = {}
		self.ref_parents = {}
		self.tooltip = None

		self.root.title("z1engine AssetKit")
		self.root.geometry("1320x760")
		self._build_ui()
		self.refresh_browser()

	def _build_ui(self):
		toolbar = ttk.Frame(self.root, padding=(8, 6))
		toolbar.pack(fill=tk.X)
		self.validate_btn = ttk.Button(toolbar, text="Validate", command=self.start_validate)
		self.validate_btn.pack(side=tk.LEFT)
		ttk.Button(toolbar, text="Import Asset...", command=self.open_import_dialog).pack(side=tk.LEFT, padx=(6, 0))
		ttk.Button(toolbar, text="Show References", command=self.show_references).pack(side=tk.LEFT, padx=(6, 0))
		ttk.Button(toolbar, text="Export Report...", command=self.export_report).pack(side=tk.LEFT, padx=(6, 0))
		ttk.Button(toolbar, text="Expand All", command=self.expand_all).pack(side=tk.LEFT, padx=(6, 0))
		ttk.Button(toolbar, text="Collapse All", command=self.collapse_all).pack(side=tk.LEFT, padx=(6, 0))
		ttk.Checkbutton(toolbar, text="Errors", variable=self.show_errors,
			command=self.refill_issues).pack(side=tk.LEFT, padx=(16, 0))
		ttk.Checkbutton(toolbar, text="Warnings", variable=self.show_warnings,
			command=self.refill_issues).pack(side=tk.LEFT, padx=(6, 0))
		ttk.Label(toolbar, text="GUID/Path:").pack(side=tk.LEFT, padx=(16, 0))
		self.search_var = tk.StringVar()
		search_entry = ttk.Entry(toolbar, textvariable=self.search_var, width=30)
		search_entry.pack(side=tk.LEFT, padx=(4, 0))
		search_entry.bind("<Return>", self.find_asset)
		ttk.Button(toolbar, text="Find", command=self.find_asset).pack(side=tk.LEFT, padx=(4, 0))
		self.summary_var = tk.StringVar(value="Ready")
		ttk.Label(toolbar, textvariable=self.summary_var).pack(side=tk.RIGHT)

		paned = ttk.PanedWindow(self.root, orient=tk.HORIZONTAL)
		paned.pack(fill=tk.BOTH, expand=True, padx=8, pady=(0, 8))

		browser_frame = ttk.LabelFrame(paned, text="Asset Browser", padding=4)
		paned.add(browser_frame, weight=1)
		self.tree = ttk.Treeview(browser_frame, selectmode="browse")
		self.tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
		vsb = ttk.Scrollbar(browser_frame, orient="vertical", command=self.tree.yview)
		vsb.pack(side=tk.RIGHT, fill=tk.Y)
		self.tree.configure(yscrollcommand=vsb.set)
		self.tree.tag_configure("error", foreground="#c00000")
		self.tree.tag_configure("warning", foreground="#9a6700")
		self.tree.bind("<<TreeviewSelect>>", self.on_browser_select)

		right_pane = ttk.PanedWindow(paned, orient=tk.VERTICAL)
		paned.add(right_pane, weight=2)

		issues_frame = ttk.LabelFrame(right_pane, text="Warnings and Errors", padding=4)
		right_pane.add(issues_frame, weight=1)
		self.issues = ttk.Treeview(issues_frame,
			columns=("sev", "file", "location", "message"), show="headings")
		self.issues.heading("sev", text="Sev")
		self.issues.heading("file", text="File")
		self.issues.heading("location", text="Location")
		self.issues.heading("message", text="Message")
		self.issues.column("sev", width=60, stretch=False)
		self.issues.column("file", width=260)
		self.issues.column("location", width=200)
		self.issues.column("message", width=420)
		self.issues.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
		ivsb = ttk.Scrollbar(issues_frame, orient="vertical", command=self.issues.yview)
		ivsb.pack(side=tk.RIGHT, fill=tk.Y)
		self.issues.configure(yscrollcommand=ivsb.set)
		self.issues.tag_configure("error", foreground="#c00000")
		self.issues.tag_configure("warning", foreground="#9a6700")
		self.issues.bind("<Double-1>", self.on_issue_double_click)

		details_frame = ttk.LabelFrame(right_pane, text="Details", padding=4)
		right_pane.add(details_frame, weight=1)
		self.details = tk.Text(details_frame, wrap=tk.WORD, state=tk.DISABLED)
		self.details.pack(fill=tk.BOTH, expand=True)
		dvsb = ttk.Scrollbar(details_frame, orient="vertical", command=self.details.yview)
		dvsb.pack(side=tk.RIGHT, fill=tk.Y)
		self.details.configure(yscrollcommand=dvsb.set)
		self.details.tag_config("link", foreground="blue", underline=1)
		self.details.tag_bind("link", "<Button-1>", self.on_link_click)
		self.details.tag_bind("link", "<Enter>", self.on_link_enter)
		self.details.tag_bind("link", "<Leave>", self.on_link_leave)
		self.tooltip = ToolTip(self.details)

		status = ttk.Frame(self.root, padding=(8, 0, 8, 6))
		status.pack(fill=tk.X)
		self.status_var = tk.StringVar(value="Ready")
		ttk.Label(status, textvariable=self.status_var).pack(side=tk.LEFT)

	# -- browser ---------------------------------------------------------------
	def refresh_browser(self):
		for item in self.tree.get_children():
			self.tree.delete(item)
		self.browser_item_map.clear()
		self.path_to_item.clear()
		self.guid_to_path.clear()
		for name, path_str in self.roots:
			path = Path(path_str)
			if not path.is_absolute():
				path = self.base_dir / path
			display = name if name else path.name
			root_id = self.tree.insert("", "end", text=display, open=True)
			self.browser_item_map[root_id] = (name, "", str(path), "root")
			if path.is_dir():
				self._insert_walk(root_id, name, path, path)

	def _insert_walk(self, parent_id, name, base, dirpath):
		entries = sorted(dirpath.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
		for entry in entries:
			rel = entry.relative_to(base).as_posix()
			if entry.is_dir():
				item_id = self.tree.insert(parent_id, "end", text=entry.name, open=False)
				self.browser_item_map[item_id] = (name, rel, str(entry), "dir")
				self.path_to_item[f"{name}\n{rel}"] = item_id
				self._insert_walk(item_id, name, base, entry)
			elif entry.is_file() and entry.suffix.lower() in (".yaml", ".py", ".glsl"):
				item_id = self.tree.insert(parent_id, "end", text=entry.name)
				self.browser_item_map[item_id] = (name, rel, str(entry), "file")
				self.path_to_item[f"{name}\n{rel}"] = item_id
				if entry.suffix.lower() == ".yaml":
					self._index_meta_guid(entry, name, rel)

	def _index_meta_guid(self, file, name, rel):
		try:
			content = file.read_text(encoding="utf-8", errors="replace")
		except OSError:
			return
		match = re.search(r"^\s*guid:\s*(\S+)", content, re.MULTILINE)
		if match:
			self.guid_to_path[match.group(1)] = (name, rel)

	def _set_open(self, item, open_):
		self.tree.item(item, open=open_)
		for child in self.tree.get_children(item):
			self._set_open(child, open_)

	def expand_all(self):
		for item in self.tree.get_children(""):
			self._set_open(item, True)

	def collapse_all(self):
		for item in self.tree.get_children(""):
			self._set_open(item, False)

	def _file_key(self, name, rel):
		return rel if not name else f"{name}/{rel}"

	def navigate_to_file(self, name, rel):
		item_id = self.path_to_item.get(f"{name}\n{rel}")
		if not item_id:
			return False
		parent = self.tree.parent(item_id)
		while parent:
			self.tree.item(parent, open=True)
			parent = self.tree.parent(parent)
		self.tree.selection_set(item_id)
		self.tree.focus(item_id)
		self.tree.see(item_id)
		self.on_browser_select(None)
		return True

	# -- validation ------------------------------------------------------------
	def start_validate(self):
		if self.running:
			return
		self.running = True
		self._worker_result = None
		self.validate_btn.config(state=tk.DISABLED)
		self.summary_var.set("Validating...")
		self.status_var.set("Scanning content roots...")
		threading.Thread(target=self._validate_worker, daemon=True).start()
		self.root.after(100, self._poll_worker)

	def _validate_worker(self):
		try:
			self._worker_result = (core.check_assets(self.roots, self.base_dir), None)
		except Exception as exc:
			self._worker_result = (None, str(exc))
		finally:
			self.running = False

	def _poll_worker(self):
		if self.running:
			self.root.after(100, self._poll_worker)
			return
		report, error = self._worker_result
		self._apply_report(report, error)

	def _apply_report(self, report, error):
		self.validate_btn.config(state=tk.NORMAL)
		if error:
			self.summary_var.set("Validation failed")
			self.status_var.set(f"Validation failed: {error}")
			messagebox.showerror("Validation failed", error)
			return
		self.report = report
		self.asset_by_file = {a.file: a for a in report.assets}
		self.issue_by_file = {}
		for issue in report.issues:
			self.issue_by_file.setdefault(issue.file, []).append(issue)
		self.ref_children = {}
		self.ref_parents = {}
		for asset in report.assets:
			kids = []
			seen = set()
			for ref in asset.refs:
				pair = (ref.target, ref.value)
				if pair in seen:
					continue
				seen.add(pair)
				kids.append(pair)
			self.ref_children[asset.file] = kids
		for asset in report.assets:
			for ref in asset.refs:
				if ref.target:
					parents = self.ref_parents.setdefault(ref.target, [])
					if asset.file not in parents:
						parents.append(asset.file)
		self.refill_issues()
		self.apply_browser_tags()
		counts = report.counts
		self.summary_var.set(
			f"{counts['assets']} assets, {counts['errors']} errors, {counts['warnings']} warnings")
		self.status_var.set(f"Validated in {report.elapsed:.2f}s")

	def refill_issues(self):
		for item in self.issues.get_children():
			self.issues.delete(item)
		if not self.report:
			return
		for issue in self.report.issues:
			if issue.severity == "error" and not self.show_errors.get():
				continue
			if issue.severity == "warning" and not self.show_warnings.get():
				continue
			sev = "ERROR" if issue.severity == "error" else "WARN"
			self.issues.insert("", "end",
				values=(sev, issue.file, issue.location, issue.message),
				tags=(issue.severity,))

	def apply_browser_tags(self):
		for item_id in self.browser_item_map:
			self.tree.item(item_id, tags=())
		if not self.report:
			return
		by_file = {}
		for issue in self.report.issues:
			by_file.setdefault(issue.file, set()).add(issue.severity)
		for item_id, (name, rel, _, _) in self.browser_item_map.items():
			key = self._file_key(name, rel)
			if key in by_file:
				tag = "error" if "error" in by_file[key] else "warning"
				self.tree.item(item_id, tags=(tag,))

	# -- details ---------------------------------------------------------------
	def _set_details(self, text, highlight_guids=False):
		self.details.config(state=tk.NORMAL)
		self.details.delete("1.0", tk.END)
		self.details.insert("1.0", text)
		if highlight_guids:
			self._highlight_guids()
		self.details.config(state=tk.DISABLED)

	def _highlight_guids(self):
		start_pos = "1.0"
		while True:
			count_var = tk.IntVar()
			pos = self.details.search(UUID_PATTERN, start_pos,
				stopindex=tk.END, regexp=True, count=count_var)
			if not pos:
				break
			end_pos = f"{pos}+{count_var.get()}c"
			guid = self.details.get(pos, end_pos)
			if guid in self.guid_to_path:
				self.details.tag_add("link", pos, end_pos)
			start_pos = end_pos

	def on_browser_select(self, event):
		selection = self.tree.selection()
		if not selection:
			return
		info = self.browser_item_map.get(selection[0])
		if not info:
			return
		name, rel, abs_path, kind = info
		key = self._file_key(name, rel)
		lines = []
		if kind in ("dir", "root"):
			lines.append(f"Directory: {abs_path}")
			lines.append(f"Root: {name or '(default)'}")
			self._set_details("\n".join(lines))
			return
		lines.append(f"File: {abs_path}")
		asset = self.asset_by_file.get(key)
		if asset:
			lines.append(f"Type: {asset.type}")
			lines.append(f"Guid: {asset.guid}")
			lines.append(f"Asset path: {asset.path}")
			lines.append("")
			lines.append(f"References ({len(asset.refs)}):")
			for ref in asset.refs:
				target = f" -> {ref.target}" if ref.target else ""
				lines.append(f"  [{ref.kind}] {ref.value}  @ {ref.location}{target}")
		else:
			lines.append("No asset metadata (run Validate).")
		issues = self.issue_by_file.get(key)
		if issues:
			lines.append("")
			lines.append(f"Issues in this file ({len(issues)}):")
			for issue in issues:
				location = f" @ {issue.location}" if issue.location else ""
				lines.append(f"  [{issue.severity}]{location}: {issue.message}")
		lines.append("")
		lines.append("--- file preview ---")
		self._set_details("\n".join(lines))
		self._append_preview(abs_path)

	def _append_preview(self, abs_path):
		path = Path(abs_path)
		try:
			size = path.stat().st_size
		except OSError:
			self._append_details("\n(unable to stat file)")
			return
		self.details.config(state=tk.NORMAL)
		if size > PREVIEW_LIMIT:
			self.details.insert(tk.END, f"\n(file too large to preview: {size} bytes)")
			self.details.config(state=tk.DISABLED)
			return
		try:
			content = path.read_text(encoding="utf-8")
		except UnicodeDecodeError:
			self.details.insert(tk.END, "\n(binary or non-UTF-8 file, preview not shown)")
			self.details.config(state=tk.DISABLED)
			return
		except OSError:
			self.details.insert(tk.END, "\n(unable to read file)")
			self.details.config(state=tk.DISABLED)
			return
		self.details.insert(tk.END, "\n" + content)
		self._highlight_guids()
		self.details.config(state=tk.DISABLED)

	def _append_details(self, text):
		self.details.config(state=tk.NORMAL)
		self.details.insert(tk.END, text)
		self.details.config(state=tk.DISABLED)

	# -- guid link navigation ----------------------------------------------------
	def get_guid_at(self, x, y):
		try:
			index = self.details.index(f"@{x},{y}")
			tags = self.details.tag_names(index)
			if "link" in tags:
				ranges = self.details.tag_ranges("link")
				for i in range(0, len(ranges), 2):
					start = ranges[i]
					end = ranges[i + 1]
					if self.details.compare(start, "<=", index) and self.details.compare(index, "<", end):
						return self.details.get(start, end)
		except tk.TclError:
			pass
		return None

	def on_link_click(self, event):
		guid = self.get_guid_at(event.x, event.y)
		if not guid:
			return
		target = self.guid_to_path.get(guid)
		if target:
			self.navigate_to_file(target[0], target[1])
		else:
			messagebox.showinfo("Info", "GUID not found in index.")

	def on_link_enter(self, event):
		self.details.config(cursor="hand2")
		guid = self.get_guid_at(event.x, event.y)
		if guid and guid in self.guid_to_path:
			name, rel = self.guid_to_path[guid]
			self.tooltip.show(self._file_key(name, rel), event.x_root, event.y_root)

	def on_link_leave(self, event):
		self.details.config(cursor="")
		self.tooltip.hide()

	# -- issues ------------------------------------------------------------------
	def on_issue_double_click(self, event):
		item = self.issues.identify_row(event.y)
		if not item:
			return
		values = self.issues.item(item, "values")
		if not values:
			return
		file_key = values[1]
		for item_id, (name, rel, _, _) in self.browser_item_map.items():
			if self._file_key(name, rel) == file_key:
				self.navigate_to_file(name, rel)
				break

	# -- guid/path search -------------------------------------------------------------
	def find_asset(self, event=None):
		query = self.search_var.get().strip()
		if not query:
			return
		target = self.guid_to_path.get(query)
		if target and self.navigate_to_file(target[0], target[1]):
			self.status_var.set(f"Found: {query}")
			return
		for asset in self.asset_by_file.values():
			if asset.guid == query or asset.path == query or asset.file == query:
				rel = asset.file[len(asset.root_name) + 1:] if asset.root_name else asset.file
				if self.navigate_to_file(asset.root_name, rel):
					self.status_var.set(f"Found: {query}")
					return
		messagebox.showinfo("Find", f"No asset found for: {query}")

	# -- reference viewer ---------------------------------------------------------------
	def show_references(self):
		selection = self.tree.selection()
		if not selection:
			messagebox.showinfo("References", "Select an asset in the browser first.")
			return
		info = self.browser_item_map.get(selection[0])
		if not info:
			return
		name, rel, _, kind = info
		if kind != "file":
			messagebox.showinfo("References", "Select an asset file in the browser first.")
			return
		key = self._file_key(name, rel)
		if not self.report:
			messagebox.showinfo("References", "Run Validate first.")
			return
		if key not in self.asset_by_file:
			messagebox.showinfo("References", f"No asset metadata for: {key}")
			return
		ReferenceViewer(self.root, key, self.ref_children, self.ref_parents, self.issue_by_file)

	# -- import --------------------------------------------------------------------
	def open_import_dialog(self):
		file_path = filedialog.askopenfilename(
			initialdir=self.base_dir / "asset",
			title="Select Asset to Import",
			filetypes=(("All Files", "*.*"), ("Textures", "*.png;*.jpg;*.tga"),
				("Models", "*.glb;*.gltf;*.obj")))
		if not file_path:
			return
		self.show_import_settings(file_path)

	def show_import_settings(self, source_file):
		exe = self._find_import_exe()
		if exe is None:
			messagebox.showwarning("Warning",
				"assetkit.exe not found in engine/bin.\nBuild the solution first (python dev/z1.py compile).")
			return
		dialog = tk.Toplevel(self.root)
		dialog.title("Import Settings")
		dialog.geometry("400x300")

		ttk.Label(dialog, text=f"Importing: {Path(source_file).name}").pack(pady=10)
		ttk.Label(dialog, text="Output Path (relative to content):").pack(anchor=tk.W, padx=10)
		out_var = tk.StringVar(value=Path(source_file).stem)
		ttk.Entry(dialog, textvariable=out_var).pack(fill=tk.X, padx=10)
		ttk.Label(dialog, text="Type (Auto-detect if empty):").pack(anchor=tk.W, padx=10)
		type_var = tk.StringVar()
		ttk.Combobox(dialog, textvariable=type_var, values=["", "texture", "gltf", "obj"]).pack(fill=tk.X, padx=10)
		ttk.Label(dialog, text="Sampler (Texture only):").pack(anchor=tk.W, padx=10)
		sampler_var = tk.StringVar(value="linear")
		ttk.Combobox(dialog, textvariable=sampler_var, values=["linear", "nearest"]).pack(fill=tk.X, padx=10)
		ttk.Label(dialog, text="Wrap (Texture only):").pack(anchor=tk.W, padx=10)
		wrap_var = tk.StringVar(value="repeat")
		ttk.Combobox(dialog, textvariable=wrap_var, values=["repeat", "mirror", "clamp", "border"]).pack(fill=tk.X, padx=10)

		def run_import():
			out_path = out_var.get().strip()
			if not out_path:
				messagebox.showerror("Error", "Output path must not be empty.", parent=dialog)
				return
			cmd = [str(exe), source_file, out_path]
			if type_var.get():
				cmd.extend(["--type", type_var.get()])
			if sampler_var.get():
				cmd.extend(["--sampler", sampler_var.get()])
			if wrap_var.get():
				cmd.extend(["--wrap", wrap_var.get()])
			self.status_var.set("Importing...")
			try:
				result = subprocess.run(cmd, capture_output=True, text=True, cwd=str(self.base_dir))
			except OSError as exc:
				messagebox.showerror("Error", f"Failed to run assetkit: {exc}", parent=dialog)
				return
			if result.returncode == 0:
				messagebox.showinfo("Success", f"Import successful!\n{result.stdout}", parent=dialog)
				dialog.destroy()
				self.refresh_browser()
				self.start_validate()
			else:
				messagebox.showerror("Error",
					f"Import failed:\n{result.stderr}\n{result.stdout}", parent=dialog)

		ttk.Button(dialog, text="Import", command=run_import).pack(pady=20)

	def _find_import_exe(self):
		bin_dir = self.base_dir / "engine" / "bin"
		for name in ("assetkit.exe", "importer.exe"):
			candidate = bin_dir / name
			if candidate.exists():
				return candidate
		return None

	# -- export ----------------------------------------------------------------------
	def export_report(self):
		if not self.report:
			messagebox.showinfo("Export", "Run Validate first.")
			return
		path = filedialog.asksaveasfilename(
			defaultextension=".json",
			filetypes=[("JSON", "*.json")],
			initialfile="assetkit_report.json")
		if not path:
			return
		try:
			with open(path, "w", encoding="utf-8", newline="\n") as f:
				json.dump(core.report_to_dict(self.report), f, indent="\t", ensure_ascii=False)
		except OSError as exc:
			messagebox.showerror("Export failed", str(exc))
			return
		self.status_var.set(f"Report written: {path}")


class ReferenceViewer(tk.Toplevel):
	"""Horizontal reference tree: center node, parents to the left, children right."""

	def __init__(self, parent, center, children_map, parents_map, issue_map):
		super().__init__(parent)
		self.center = center
		self.children_map = children_map
		self.parents_map = parents_map
		self.issue_map = issue_map
		self.expanded = set()
		self.visible = {}
		self.node_rects = {}
		self.tag_to_key = {}
		self.font = tkfont.nametofont("TkDefaultFont")
		self.title(f"References - {center}")
		self.geometry("920x620")
		self._build_ui()
		self._toggle(center)

	def _build_ui(self):
		ttk.Label(self, text="Center = selected asset; left = referencers (parents); "
			"right = referenced assets (children). Click a node to expand/collapse.",
			padding=(8, 4)).pack(fill=tk.X)
		container = ttk.Frame(self)
		container.pack(fill=tk.BOTH, expand=True)
		self.canvas = tk.Canvas(container, bg="#ffffff", highlightthickness=0)
		vsb = ttk.Scrollbar(container, orient="vertical", command=self.canvas.yview)
		hsb = ttk.Scrollbar(container, orient="horizontal", command=self.canvas.xview)
		self.canvas.configure(yscrollcommand=vsb.set, xscrollcommand=hsb.set)
		vsb.pack(side=tk.RIGHT, fill=tk.Y)
		hsb.pack(side=tk.BOTTOM, fill=tk.X)
		self.canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
		self.canvas.bind("<Button-1>", self._on_click)

	def _node_label(self, key):
		if isinstance(key, tuple):
			return f"(missing) {key[1]}"
		label = key
		for suffix in (".yaml", ".py", ".glsl"):
			if label.endswith(suffix):
				label = label[:-len(suffix)]
				break
		if len(label) > 44:
			label = label[:20] + "..." + label[-20:]
		return label

	def _has_neighbors(self, key):
		if isinstance(key, tuple):
			return False
		return bool(self.children_map.get(key) or self.parents_map.get(key))

	def _recompute(self):
		visible = {self.center: 0}
		stack = [self.center]
		while stack:
			key = stack.pop()
			if key not in self.expanded or isinstance(key, tuple):
				continue
			depth = visible[key]
			for target, value in self.children_map.get(key, ()):
				node = target if target else ("missing", value)
				if node not in visible:
					visible[node] = depth + 1
					stack.append(node)
			for parent in self.parents_map.get(key, ()):
				if parent not in visible:
					visible[parent] = depth - 1
					stack.append(parent)
		self.visible = visible

	def _node_colors(self, key):
		if isinstance(key, tuple):
			return "#ffe0e0", "#c00000", "#c00000"
		issues = self.issue_map.get(key)
		if issues and any(i.severity == "error" for i in issues):
			return "#ffe0e0", "#c00000", "#7a0000"
		if issues:
			return "#fff3dc", "#b07800", "#7a5200"
		if key == self.center:
			return "#e3f0ff", "#1a5fb4", "#0a3d80"
		return "#ffffff", "#a0a0a0", "#202020"

	def _redraw(self):
		self.canvas.delete("all")
		self.node_rects = {}
		self.tag_to_key = {}
		if not self.visible:
			return
		columns = {}
		for key, depth in self.visible.items():
			columns.setdefault(depth, []).append(key)
		depths = sorted(columns)
		node_h = 38
		gap_y = 16
		margin = 24
		col_gap = 56
		metrics = {}
		for key in self.visible:
			label = self._node_label(key)
			if key in self.expanded:
				label += "  [-]"
			elif self._has_neighbors(key):
				label += "  [+]"
			width = self.font.measure(label) + 28
			width = max(150, min(360, width))
			metrics[key] = (label, width)
		col_widths = {depth: max(metrics[k][1] for k in keys) for depth, keys in columns.items()}
		x_centers = {}
		x = margin
		for depth in depths:
			x_centers[depth] = x + col_widths[depth] / 2
			x += col_widths[depth] + col_gap
		canvas_w = sum(col_widths.values()) + col_gap * (len(depths) - 1) + 2 * margin
		heights = {depth: len(keys) * node_h + (len(keys) - 1) * gap_y for depth, keys in columns.items()}
		canvas_h = max(heights.values()) + 2 * margin
		y_centers = {}
		for depth, keys in columns.items():
			y = (canvas_h - heights[depth]) / 2 + node_h / 2
			for key in keys:
				y_centers[key] = y
				y += node_h + gap_y
		for key in self.visible:
			if isinstance(key, tuple):
				continue
			for target, value in self.children_map.get(key, ()):
				child = target if target else ("missing", value)
				if child in y_centers:
					self.canvas.create_line(
						x_centers[self.visible[key]] + metrics[key][1] / 2, y_centers[key],
						x_centers[self.visible[child]] - metrics[child][1] / 2, y_centers[child],
						fill="#c00000" if isinstance(child, tuple) else "#8a8a8a")
		for key, (label, width) in metrics.items():
			cx = x_centers[self.visible[key]]
			cy = y_centers[key]
			x0, y0 = cx - width / 2, cy - node_h / 2
			x1, y1 = cx + width / 2, cy + node_h / 2
			fill, outline, fg = self._node_colors(key)
			tag = f"node:{len(self.tag_to_key)}"
			self.tag_to_key[tag] = key
			self.canvas.create_rectangle(x0, y0, x1, y1, fill=fill, outline=outline, width=2, tags=(tag,))
			self.canvas.create_text(cx, cy, text=label, fill=fg, font=self.font,
				width=max(20, width - 16), tags=(tag,))
			self.node_rects[tag] = (x0, y0, x1, y1)
		self.canvas.configure(scrollregion=(0, 0, canvas_w, canvas_h))

	def _on_click(self, event):
		for tag, (x0, y0, x1, y1) in self.node_rects.items():
			if x0 <= event.x <= x1 and y0 <= event.y <= y1:
				self._toggle(self.tag_to_key[tag])
				return

	def _toggle(self, key):
		if isinstance(key, tuple):
			return
		if key in self.expanded:
			self.expanded.discard(key)
		else:
			self.expanded.add(key)
		self._recompute()
		self._redraw()


def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="assetkit",
		description="Unified asset tool: browser, validation, import (GUI, or --check for headless).")
	parser.add_argument("--root", action="append", default=[], metavar="[NAME:]PATH",
		help="additional content root (repeatable); defaults: content, engine:engine/content")
	parser.add_argument("--check", action="store_true",
		help="headless validation: print report and exit (no GUI)")
	parser.add_argument("--json", metavar="FILE", help="write JSON report to FILE (with --check)")
	args = parser.parse_args(argv)
	roots = list(core.DEFAULT_ROOTS)
	for spec in args.root:
		parsed = core.parse_root_spec(spec)
		if parsed:
			roots.append(parsed)
	if args.check:
		return core.run_headless(roots, args.json)
	app_root = tk.Tk()
	AssetKitApp(app_root, roots)
	app_root.mainloop()
	return 0


if __name__ == "__main__":
	sys.exit(main())
