# [AI-GENERATED] This file was generated by an AI agent.
"""z1 dev tools -- unified CLI entry point for z1engine development."""

import argparse
import importlib
import sys
from pathlib import Path

# Ensure dev/commands is importable
sys.path.insert(0, str(Path(__file__).resolve().parent))

COMMANDS = {
	"generate":         ("commands.generate",         "Regenerate VS project files from premake5"),
	"compile":          ("commands.compile",          "Build the solution (Debug|x64 by default)"),
	"format":           ("commands.format_cmd",       "Format source code (tabs, trailing whitespace, CRLF)"),
	"validate-shaders": ("commands.validate_shaders", "Validate all GLSL shaders"),
	"test":             ("commands.test",             "Discover and run test executables"),
	"benchmark":        ("commands.benchmark",        "Run benchmark suites and compare baselines"),
	"smoke":            ("commands.smoke",            "Run editor smoke test (--one-frame)"),
	"dcv":              ("commands.dcv",              "Full develop-compile-verify loop"),
	"release":          ("commands.release",          "Package release folder"),
}

def print_usage():
	print("z1 dev tools")
	print()
	print("Usage: python dev/z1.py <command> [options]")
	print()
	print("Commands:")
	max_len = max(len(name) for name in COMMANDS)
	for name, (_, desc) in COMMANDS.items():
		print(f"  {name:<{max_len + 2}}{desc}")
	print()
	print("Run 'python dev/z1.py <command> --help' for command-specific usage.")

def main():
	if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
		print_usage()
		sys.exit(0)

	cmd_name = sys.argv[1]
	if cmd_name not in COMMANDS:
		print(f"Unknown command: {cmd_name}")
		print()
		print_usage()
		sys.exit(1)

	module_name, _ = COMMANDS[cmd_name]
	mod = importlib.import_module(module_name)
	sys.exit(mod.main(sys.argv[2:]))

if __name__ == "__main__":
	main()
