// [AI-GENERATED] This file was generated by an AI agent.

#include "z1engine.h"

#include <fstream>

using namespace z1;

struct OurApp : Application {
	void init() override {};
};

static int check_guid(std::string const& label, Guid const& guid, std::string const& expected) {
	if (guid.to_string() != expected) {
		std::cerr << "FAIL: " << label << " = " << guid.to_string() << ", expected " << expected << std::endl;
		return 1;
	}
	return 0;
}

int main() {
	g_args.set("no-window", "1");
	OurApp app;
	app.init();

	int failures = 0;

	// derivation vectors, shared with utils/z1_guid.py
	failures += check_guid("engine mesh/SM_Cube", Guid::from_path("mesh/SM_Cube"), "000000009a9d0329a8631e5aa760403e");
	failures += check_guid("engine texture/T_white", Guid::from_root_and_path("engine", "texture/T_white"), "0000000053bd4dbb9fec70d82f7065ae");
	failures += check_guid("default root MI_HappyFace", Guid::from_root_and_path("", "MI_HappyFace"), "7c0104ee0d53c15665831faa784b0ff3");
	failures += check_guid("default root mesh/SM_Cube", Guid::from_root_and_path("", "mesh/SM_Cube"), "b05388edd50aecc6b92a33f88dcba71f");

	// the same path under different roots must not collide
	if (Guid::from_path("mesh/SM_Cube") == Guid::from_root_and_path("", "mesh/SM_Cube")) {
		std::cerr << "FAIL: root is not part of the id" << std::endl;
		++failures;
	}

	// engine prefix and the foreign flip rule
	{
		if (Guid::from_path("any/engine/path").m_data[0] != 0) {
			std::cerr << "FAIL: engine id does not keep a zero prefix" << std::endl;
			++failures;
		}

		Guid flipped = Guid::from_hash(0x0ULL, 0x1234ULL, false);
		if (flipped.m_data[0] != 0x80000000u) {
			std::cerr << "FAIL: foreign zero prefix was not flipped" << std::endl;
			++failures;
		}

		Guid engine_asset = Guid::from_hash(0xDEADBEEF00000000ULL, 0x1234ULL, true);
		if (engine_asset.m_data[0] != 0u) {
			std::cerr << "FAIL: engine hash range was not truncated" << std::endl;
			++failures;
		}

		Guid foreign = Guid::from_hash(0xDEADBEEF00000000ULL, 0x1234ULL, false);
		if (foreign.to_string().compare(0, 8, "deadbeef") != 0) {
			std::cerr << "FAIL: non-zero foreign prefix was altered" << std::endl;
			++failures;
		}

		for (int i = 0; i < 64; ++i) {
			Guid guid = Guid::from_root_and_path("", "sample/path_" + std::to_string(i));
			if (guid.m_data[0] == 0) {
				std::cerr << "FAIL: foreign id carries the engine prefix" << std::endl;
				++failures;
				break;
			}
		}
	}

	// text form: round trip, dashes tolerated, anything else invalid
	{
		Guid reference = Guid::from_path("mesh/SM_Cube");
		if (Guid::from_string(reference.to_string()) != reference) {
			std::cerr << "FAIL: text round trip" << std::endl;
			++failures;
		}
		if (Guid::from_string("00000000-9a9d-0329-a863-1e5aa760403e") != reference) {
			std::cerr << "FAIL: dashed text form did not parse" << std::endl;
			++failures;
		}
		if (Guid::from_string("mesh/SM_Cube").is_valid() || Guid::from_string("").is_valid()
			|| Guid::from_string("00000000000000000000000000000000").is_valid()
			|| Guid::from_string("0000000000000000000000000000000").is_valid()
			|| Guid::from_string("000000000000000000000000000000000").is_valid()
			|| Guid::from_string("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz").is_valid()) {
			std::cerr << "FAIL: invalid text parsed as a valid guid" << std::endl;
			++failures;
		}
	}

	// the scanned engine content must resolve by path and by id
	{
		auto& assets = *g_runtime_context.m_asset_manager;
		Guid cube = assets.resolve_guid("mesh/SM_Cube");
		failures += check_guid("resolve mesh/SM_Cube", cube, "000000009a9d0329a8631e5aa760403e");
		if (assets.resolve_guid(cube.to_string()) != cube) {
			std::cerr << "FAIL: hex reference did not resolve" << std::endl;
			++failures;
		}
	}

	// a stored guid is informational: scanning derives the id from root + path
	{
		Filepath sandbox_root = FileSystem::get_root_path("") / "sandbox-tests" / "test_guid";
		std::filesystem::remove_all(sandbox_root);
		std::filesystem::create_directories(sandbox_root);

		std::ofstream out(sandbox_root / "T_stale.yaml");
		out << "meta:\n"
			<< "  guid: 11111111-2222-3333-4444-555555555555\n"
			<< "  type: texture2d\n"
			<< "  path: sandbox-tests/test_guid/T_stale\n"
			<< "  extra: ~\n";
		out.close();

		g_runtime_context.m_asset_manager->scan_content();

		Guid expected = Guid::from_root_and_path("", "sandbox-tests/test_guid/T_stale");
		Guid stale = Guid::from_string("11111111-2222-3333-4444-555555555555");

		if (expected == stale) {
			std::cerr << "FAIL: derived id matched the stale stored id" << std::endl;
			++failures;
		}
		if (!g_runtime_context.m_asset_manager->has_asset(expected)) {
			std::cerr << "FAIL: derived id is not registered" << std::endl;
			++failures;
		}
		if (g_runtime_context.m_asset_manager->has_asset(stale)) {
			std::cerr << "FAIL: stale stored id was registered" << std::endl;
			++failures;
		}
		if (g_runtime_context.m_asset_manager->resolve_guid("sandbox-tests/test_guid/T_stale") != expected) {
			std::cerr << "FAIL: path reference did not resolve to the derived id" << std::endl;
			++failures;
		}

		std::filesystem::remove_all(sandbox_root);
		g_runtime_context.m_asset_manager->scan_content();
	}

	if (failures == 0) {
		std::cout << "test_guid: all checks passed" << std::endl;
		return 0;
	}
	std::cerr << "test_guid: " << failures << " failure(s)" << std::endl;
	return 1;
}
