// [AI-GENERATED] This file was generated by an AI agent.
#include "pch.h"

#include "util/prober.h"

#include "core/core.h"
#include "core/window.h"

#include "glad/glad.h"
#include "glfw/glfw3.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

#ifdef ENABLE_PROBING

namespace z1::prober {

	namespace {

		constexpr uint32_t kMaxSlots = 32;
		constexpr uint32_t kGpuQueryRing = 4;

		struct Slot {
			char const* name = nullptr;
			bool unitless = false;

			// window (reset on every report)
			double win_sum = 0.0;
			double win_min = 0.0;
			double win_max = 0.0;
			uint32_t win_count = 0;

			// session (never reset)
			double run_sum = 0.0;
			double run_min = 0.0;
			double run_max = 0.0;
			uint32_t run_count = 0;
		};

		Slot g_slots[kMaxSlots];
		uint32_t g_slot_count = 0;

		bool g_enabled = false;
		bool g_quiet = false;
		bool g_gpu_enabled = true;
		bool g_finish_probe = false;
		int g_report_every = 120;

		uint64_t g_frame_count = 0;
		uint32_t g_frames_since_report = 0;
		std::chrono::steady_clock::time_point g_frame_start;

		// GPU timer query ring (frames in flight write to successive queries, results are resolved
		// without blocking; on macOS availability lags the swap so some frames are missed).
		GLuint g_gpu_queries[kGpuQueryRing] = { 0, 0, 0, 0 };
		bool g_gpu_pending[kGpuQueryRing] = { false, false, false, false };
		bool g_gpu_begun[kGpuQueryRing] = { false, false, false, false };
		uint32_t g_gpu_next = 0;
		int g_gpu_current = -1;
		uint64_t g_gpu_misses = 0;
		uint64_t g_gpu_samples = 0;
		bool g_reported_environment = false;

		// Frame counters (reset every frame after being recorded as PROBE values).
		constexpr uint32_t kMaxCounters = 16;
		struct CounterSlot {
			char const* name = nullptr;
			double sum = 0.0;
		};
		CounterSlot g_counters[kMaxCounters];
		uint32_t g_counter_count = 0;

		// FNV-style rolling hash of binding-related calls, reported as "layout_hash".
		constexpr uint64_t kHashSeed = 1469598103934665603ull;
		uint64_t g_layout_hash = kHashSeed;

		bool env_flag(char const* name, bool fallback) {
			char const* value = std::getenv(name);
			if (!value) {
				return fallback;
			}
			return value[0] != '0';
		}

		// Numeric values are pre-formatted with printf style and logged as arguments so that no
		// log message ever contains fmt placeholders by accident.
		void log_line(char* line) {
			CORE_INFO("{0}", line);
		}

		Slot& find_slot(char const* name, bool unitless) {
			for (uint32_t i = 0; i < g_slot_count; ++i) {
				if (std::strcmp(g_slots[i].name, name) == 0) {
					return g_slots[i];
				}
			}
			if (g_slot_count >= kMaxSlots) {
				return g_slots[kMaxSlots - 1];
			}
			Slot& slot = g_slots[g_slot_count++];
			slot.name = name;
			slot.unitless = unitless;
			return slot;
		}

		void report_environment() {
			int window_w = 0, window_h = 0, fb_w = 0, fb_h = 0;
			float scale_x = 0.0f, scale_y = 0.0f;
			GLFWwindow* glfw_window = static_cast<GLFWwindow*>(g_runtime_context.m_window->get_native_window());
			if (glfw_window) {
				glfwGetWindowSize(glfw_window, &window_w, &window_h);
				glfwGetFramebufferSize(glfw_window, &fb_w, &fb_h);
				glfwGetWindowContentScale(glfw_window, &scale_x, &scale_y);
			}
			int monitor_count = 0;
			GLFWmonitor** monitors = glfwGetMonitors(&monitor_count);
			char const* monitor_name = (monitors && monitor_count > 0) ? glfwGetMonitorName(monitors[0]) : "none";
			char const* renderer = reinterpret_cast<char const*>(glGetString(GL_RENDERER));
			char const* version = reinterpret_cast<char const*>(glGetString(GL_VERSION));
			char const* vendor = reinterpret_cast<char const*>(glGetString(GL_VENDOR));

			char buf[320];
			std::snprintf(buf, sizeof(buf), "[probe] window=%dx%d framebuffer=%dx%d content-scale=%.2fx%.2f monitors=%d (%s)",
				window_w, window_h, fb_w, fb_h, static_cast<double>(scale_x), static_cast<double>(scale_y), monitor_count, monitor_name);
			log_line(buf);
			std::snprintf(buf, sizeof(buf), "[probe] gpu: %s | %s | %s",
				vendor ? vendor : "?", renderer ? renderer : "?", version ? version : "?");
			log_line(buf);
			g_reported_environment = true;
		}

		void report_window() {
			double frame_avg = 0.0;
			for (uint32_t i = 0; i < g_slot_count; ++i) {
				if (std::strcmp(g_slots[i].name, "frame") == 0 && g_slots[i].win_count > 0) {
					frame_avg = g_slots[i].win_sum / static_cast<double>(g_slots[i].win_count);
					break;
				}
			}
			double const fps = frame_avg > 0.0 ? 1000.0 / frame_avg : 0.0;

			char buf[256];
			std::snprintf(buf, sizeof(buf), "[probe] frame=%llu window=%u fps=%.1f",
				static_cast<unsigned long long>(g_frame_count), g_frames_since_report, fps);
			log_line(buf);

			for (uint32_t i = 0; i < g_slot_count; ++i) {
				Slot& slot = g_slots[i];
				if (slot.win_count == 0) {
					continue;
				}
				double const avg = slot.win_sum / static_cast<double>(slot.win_count);
				if (slot.unitless) {
					std::snprintf(buf, sizeof(buf), "[probe]   %-16s value=%.2f", slot.name, avg);
				} else {
					std::snprintf(buf, sizeof(buf), "[probe]   %-16s avg=%7.3f ms  min=%7.3f  max=%7.3f  n=%u",
						slot.name, avg, slot.win_min, slot.win_max, slot.win_count);
				}
				log_line(buf);
				slot.win_sum = 0.0;
				slot.win_min = 0.0;
				slot.win_max = 0.0;
				slot.win_count = 0;
			}
			if (g_gpu_enabled) {
				std::snprintf(buf, sizeof(buf), "[probe]   gpu-queries      samples=%llu misses=%llu",
					static_cast<unsigned long long>(g_gpu_samples), static_cast<unsigned long long>(g_gpu_misses));
				log_line(buf);
			}
			g_frames_since_report = 0;
		}

		void resolve_gpu_queries() {
			if (!g_gpu_enabled) {
				return;
			}
			for (uint32_t i = 0; i < kGpuQueryRing; ++i) {
				if (!g_gpu_pending[i] || g_gpu_begun[i]) {
					continue;
				}
				GLint available = 0;
				glGetQueryObjectiv(g_gpu_queries[i], GL_QUERY_RESULT_AVAILABLE, &available);
				if (available == 0) {
					continue;
				}
				GLuint64 elapsed_ns = 0;
				glGetQueryObjectui64v(g_gpu_queries[i], GL_QUERY_RESULT, &elapsed_ns);
				g_gpu_pending[i] = false;
				++g_gpu_samples;
				record_scope("gpu", static_cast<double>(elapsed_ns) / 1000000.0);
			}
		}

	} // namespace

	void configure_from_env() {
		if (g_enabled) {
			return;
		}
		g_enabled = true;
		g_quiet = env_flag("Z1_PROBE_QUIET", false);
		g_gpu_enabled = !env_flag("Z1_PROBE_NO_GPU", false);
		g_finish_probe = env_flag("Z1_PROBE_FINISH", false);
		if (char const* every = std::getenv("Z1_PROBE_EVERY")) {
			int const parsed = std::atoi(every);
			g_report_every = parsed >= 0 ? parsed : g_report_every;
		}

		char const* vsync = std::getenv("Z1_PROBE_VSYNC");
		if (vsync) {
			bool const enabled = vsync[0] != '0';
			glfwSwapInterval(enabled ? 1 : 0);
			CORE_INFO("[probe] vsync override: {0}", enabled ? 1 : 0);
		}

		if (g_gpu_enabled) {
			glGenQueries(kGpuQueryRing, g_gpu_queries);
			GLenum const err = glGetError();
			if (err != GL_NO_ERROR) {
				g_gpu_enabled = false;
				CORE_WARN("[probe] gpu timer queries unavailable (gl error 0x{0:x}), gpu timing disabled", static_cast<unsigned>(err));
			}
		}

		CORE_INFO("[probe] probing enabled (report every {0} frames, gpu timers {1}, finish probe {2})",
			g_report_every, g_gpu_enabled ? "on" : "off", g_finish_probe ? "on" : "off");
	}

	void begin_frame() {
		if (!g_enabled) {
			return;
		}
		g_frame_start = std::chrono::steady_clock::now();
	}

	void end_frame() {
		if (!g_enabled) {
			return;
		}
		++g_frame_count;
		++g_frames_since_report;
		record_scope("frame", ms_since(g_frame_start));

		// Frame counters become ordinary report values (per-frame counts) before being reset.
		for (uint32_t i = 0; i < g_counter_count; ++i) {
			record_value(g_counters[i].name, g_counters[i].sum);
			g_counters[i].sum = 0.0;
		}
		record_value("layout_hash", static_cast<double>(g_layout_hash & 0xffffffffull));
		g_layout_hash = kHashSeed;

		if (!g_reported_environment) {
			report_environment();
		}
		if (g_report_every > 0 && !g_quiet && g_frames_since_report >= static_cast<uint32_t>(g_report_every)) {
			report_window();
		}
	}

	void count(char const* name, double value) {
		if (!g_enabled) {
			return;
		}
		for (uint32_t i = 0; i < g_counter_count; ++i) {
			if (std::strcmp(g_counters[i].name, name) == 0) {
				g_counters[i].sum += value;
				return;
			}
		}
		if (g_counter_count < kMaxCounters) {
			g_counters[g_counter_count++] = { name, value };
		}
	}

	void hash_mix(uint64_t value) {
		if (!g_enabled) {
			return;
		}
		g_layout_hash ^= value + 0x9e3779b97f4a7c15ull + (g_layout_hash << 6) + (g_layout_hash >> 2);
	}

	void record_scope(char const* name, double ms) {
		if (!g_enabled) {
			return;
		}
		Slot& slot = find_slot(name, false);
		if (slot.win_count == 0) {
			slot.win_min = ms;
			slot.win_max = ms;
		}
		slot.win_min = ms < slot.win_min ? ms : slot.win_min;
		slot.win_max = ms > slot.win_max ? ms : slot.win_max;
		slot.win_sum += ms;
		++slot.win_count;

		if (slot.run_count == 0) {
			slot.run_min = ms;
			slot.run_max = ms;
		}
		slot.run_min = ms < slot.run_min ? ms : slot.run_min;
		slot.run_max = ms > slot.run_max ? ms : slot.run_max;
		slot.run_sum += ms;
		++slot.run_count;
	}

	void record_value(char const* name, double value) {
		if (!g_enabled) {
			return;
		}
		Slot& slot = find_slot(name, true);
		slot.win_sum += value;
		++slot.win_count;
		slot.run_sum += value;
		++slot.run_count;
	}

	void gpu_begin_frame() {
		if (!g_enabled || !g_gpu_enabled) {
			return;
		}
		resolve_gpu_queries();

		uint32_t const slot = g_gpu_next;
		g_gpu_next = (g_gpu_next + 1) % kGpuQueryRing;
		if (g_gpu_pending[slot]) {
			// previous query on this ring slot never became available: skip this frame
			++g_gpu_misses;
			g_gpu_current = -1;
			return;
		}
		g_gpu_pending[slot] = true;
		g_gpu_begun[slot] = true;
		g_gpu_current = static_cast<int>(slot);
		glBeginQuery(GL_TIME_ELAPSED, g_gpu_queries[slot]);
	}

	void gpu_end_frame() {
		if (!g_enabled || !g_gpu_enabled) {
			return;
		}
		if (g_gpu_current >= 0) {
			uint32_t const slot = static_cast<uint32_t>(g_gpu_current);
			glEndQuery(GL_TIME_ELAPSED);
			g_gpu_begun[slot] = false;
			g_gpu_current = -1;
		}
		if (g_finish_probe) {
			std::chrono::steady_clock::time_point const start = std::chrono::steady_clock::now();
			glFinish();
			record_scope("gpu_drain", ms_since(start));
		}
	}

	void print_summary() {
		if (!g_enabled) {
			return;
		}
		double const frame_avg = [&]() {
			for (uint32_t i = 0; i < g_slot_count; ++i) {
				if (std::strcmp(g_slots[i].name, "frame") == 0 && g_slots[i].run_count > 0) {
					return g_slots[i].run_sum / static_cast<double>(g_slots[i].run_count);
				}
			}
			return 0.0;
		}();

		char buf[256];
		std::snprintf(buf, sizeof(buf), "[probe] session summary: frames=%llu avg-frame=%.3f ms fps=%.1f",
			static_cast<unsigned long long>(g_frame_count), frame_avg, frame_avg > 0.0 ? 1000.0 / frame_avg : 0.0);
		log_line(buf);
		for (uint32_t i = 0; i < g_slot_count; ++i) {
			Slot& slot = g_slots[i];
			if (slot.run_count == 0) {
				continue;
			}
			double const avg = slot.run_sum / static_cast<double>(slot.run_count);
			if (slot.unitless) {
				std::snprintf(buf, sizeof(buf), "[probe]   %-16s avg=%.2f", slot.name, avg);
			} else {
				std::snprintf(buf, sizeof(buf), "[probe]   %-16s avg=%7.3f ms  min=%7.3f  max=%7.3f  n=%u",
					slot.name, avg, slot.run_min, slot.run_max, slot.run_count);
			}
			log_line(buf);
		}
		if (g_gpu_enabled) {
			std::snprintf(buf, sizeof(buf), "[probe]   gpu-queries      samples=%llu misses=%llu",
				static_cast<unsigned long long>(g_gpu_samples), static_cast<unsigned long long>(g_gpu_misses));
			log_line(buf);
		}
	}

} // namespace z1::prober

#endif // ENABLE_PROBING
