// [AI-GENERATED] This file was generated by an AI agent.
#pragma once

// Frame prober: lightweight CPU scope + GPU frame-time measurement, compiled in with ENABLE_PROBING.
// Unlike ENABLE_PROFILE (CPU chrome-tracing of hot paths), probing is budget oriented: per-interval
// reports and a session summary printed to the log, CPU scopes and GPU timer queries side by side.
// All macros compile to nothing when ENABLE_PROBING is not defined.
//
// Runtime knobs (ENABLE_PROBING builds only):
//   Z1_PROBE_EVERY=N  report interval in frames (default 120, 0 = no periodic reports)
//   Z1_PROBE_QUIET=1  suppress periodic reports (environment line + final summary stay)
//   Z1_PROBE_VSYNC=0|1  force the swap interval at startup (A/B testing)
//   Z1_PROBE_FINISH=1  record a timed glFinish() drain before present as gpu_drain
//   Z1_PROBE_NO_GPU=1  disable GPU timer queries
//   Z1_NO_GL_CHECK=1  skip glGetError() polling (error-check cost A/B)

#include <chrono>
#include <cstdint>

namespace z1::prober {

	// Internal helpers used by the macros (also callable directly).
	void configure_from_env();
	void begin_frame();
	void end_frame();
	void record_scope(char const* name, double ms);
	void record_value(char const* name, double value);
	void print_summary();

	// Per-frame counter: accumulated during the frame, reported (as its average) on the next report.
	void count(char const* name, double value = 1.0);
	// Mixes a value into the frame's binding-layout hash (reported as "layout_hash").
	void hash_mix(uint64_t value);

	// GPU timing hooks, called by the graphics context at frame boundaries.
	void gpu_begin_frame();
	void gpu_end_frame();

	inline double ms_since(std::chrono::steady_clock::time_point start) {
		return std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count();
	}

	struct ScopeTimer {
		char const* name;
		std::chrono::steady_clock::time_point start;

		explicit ScopeTimer(char const* scope_name) : name(scope_name), start(std::chrono::steady_clock::now()) {}
		~ScopeTimer() { record_scope(name, ms_since(start)); }
	};

}

#define Z1_PROBE_CAT_IMPL(a, b) a##b
#define Z1_PROBE_CAT(a, b) Z1_PROBE_CAT_IMPL(a, b)

#ifdef ENABLE_PROBING
#	define PROBE_CONFIGURE()        ::z1::prober::configure_from_env()
#	define PROBE_FRAME_BEGIN()      ::z1::prober::begin_frame()
#	define PROBE_FRAME_END()        ::z1::prober::end_frame()
#	define PROBE_SCOPE(name)        ::z1::prober::ScopeTimer Z1_PROBE_CAT(z1_probe_scope_, __LINE__)(name)
#	define PROBE_VALUE(name, value) ::z1::prober::record_value(name, static_cast<double>(value))
#	define PROBE_COUNT(name)        ::z1::prober::count(name)
#	define PROBE_HASH_MIX(value)    ::z1::prober::hash_mix(static_cast<uint64_t>(value))
#	define PROBE_GPU_BEGIN_FRAME()  ::z1::prober::gpu_begin_frame()
#	define PROBE_GPU_END_FRAME()    ::z1::prober::gpu_end_frame()
#	define PROBE_PRINT_SUMMARY()    ::z1::prober::print_summary()
#else
#	define PROBE_CONFIGURE()        ((void)0)
#	define PROBE_FRAME_BEGIN()      ((void)0)
#	define PROBE_FRAME_END()        ((void)0)
#	define PROBE_SCOPE(name)        ((void)0)
#	define PROBE_VALUE(name, value) ((void)0)
#	define PROBE_COUNT(name)        ((void)0)
#	define PROBE_HASH_MIX(value)    ((void)0)
#	define PROBE_GPU_BEGIN_FRAME()  ((void)0)
#	define PROBE_GPU_END_FRAME()    ((void)0)
#	define PROBE_PRINT_SUMMARY()    ((void)0)
#endif
