# [AI-GENERATED] This file was generated by an AI agent.
"""Shared utilities for z1 dev-scripts."""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Exit codes
# ---------------------------------------------------------------------------
EXIT_OK = 0
EXIT_BUILD_ERROR = 1
EXIT_VALIDATION_ERROR = 2
EXIT_RUNTIME_ERROR = 3
EXIT_CONFIG_ERROR = 4

# ---------------------------------------------------------------------------
# Status prefixes
# ---------------------------------------------------------------------------
def print_ok(msg):
	print(f"[OK] {msg}")

def print_fail(msg):
	print(f"[FAIL] {msg}")

def print_warn(msg):
	print(f"[WARN] {msg}")

def print_skip(msg):
	print(f"[SKIP] {msg}")

def print_info(msg):
	print(f"[INFO] {msg}")

def print_run(msg):
	print(f"[RUN] {msg}")

# ---------------------------------------------------------------------------
# RESULT line
# ---------------------------------------------------------------------------
def make_result(status, command, **fields):
	"""Print the RESULT JSON line and return the appropriate exit code."""
	data = {"status": status, "command": command}
	data.update(fields)
	print(f"RESULT: {json.dumps(data)}")
	if status == "ok":
		return EXIT_OK
	if status == "fail":
		return fields.get("exit_code", EXIT_BUILD_ERROR)
	if status == "warn":
		return EXIT_OK
	return EXIT_OK

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
def repo_root():
	"""Return the repository root (parent of dev/)."""
	return Path(__file__).resolve().parent.parent.parent

def normalize_path(p):
	"""Normalize a path to OS-native format."""
	return str(Path(p).resolve())

# ---------------------------------------------------------------------------
# Config normalization
# ---------------------------------------------------------------------------
_VALID_CONFIGS = {"debug": "Debug", "release": "Release", "profile": "Profile"}

def normalize_config(name):
	"""Normalize a build config name (case-insensitive). Returns None if invalid."""
	return _VALID_CONFIGS.get(name.lower()) if name else None

# ---------------------------------------------------------------------------
# Visual Studio detection
# ---------------------------------------------------------------------------
_VS_EDITIONS = ["Community", "Professional", "Enterprise"]
_VS_BASE = r"C:\Program Files\Microsoft Visual Studio\18"

def find_vs2026():
	"""Find devenv.com for VS2026. Returns path string or None."""
	for edition in _VS_EDITIONS:
		p = Path(_VS_BASE) / edition / "Common7" / "IDE" / "devenv.com"
		if p.exists():
			return str(p)
	return None

# ---------------------------------------------------------------------------
# Subprocess runner
# ---------------------------------------------------------------------------
def run_subprocess(cmd, cwd=None, timeout=None):
	"""Run a command and return (returncode, stdout, stderr).

	cmd can be a list or a string. cwd defaults to repo_root().
	"""
	if cwd is None:
		cwd = str(repo_root())
	try:
		result = subprocess.run(
			cmd,
			cwd=cwd,
			capture_output=True,
			text=True,
			timeout=timeout,
		)
		return result.returncode, result.stdout, result.stderr
	except FileNotFoundError:
		return -1, "", f"Command not found: {cmd[0] if isinstance(cmd, list) else cmd}"
	except subprocess.TimeoutExpired:
		return -2, "", f"Command timed out after {timeout}s"

# ---------------------------------------------------------------------------
# Timer helper
# ---------------------------------------------------------------------------
class Timer:
	def __init__(self):
		self._start = time.perf_counter()

	def elapsed(self):
		"""Return elapsed time as a formatted string like '12.3s'."""
		dt = time.perf_counter() - self._start
		return f"{dt:.1f}s"
