# [AI-GENERATED] This file was generated by an AI agent.
"""compile -- Build the solution via devenv.com and parse MSBuild output."""

import argparse
import re
import time
from pathlib import Path
from commands._common import (
	EXIT_BUILD_ERROR, EXIT_CONFIG_ERROR, Timer, find_vs2026, make_result,
	normalize_config, print_fail, print_info, print_ok, print_run, print_warn,
	repo_root, run_subprocess,
)

# MSBuild error/warning patterns
_RE_ERROR = re.compile(r"^(.*?)\((\d+)\):\s*error\s+\w+:\s*(.+)$", re.MULTILINE)
_RE_WARNING = re.compile(r"^(.*?)\((\d+)\):\s*warning\s+\w+:\s*(.+)$", re.MULTILINE)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 compile",
		description="Build the z1engine solution.",
	)
	parser.add_argument("--config", default="Debug",
						help="Build configuration: Debug, Release, Profile (case-insensitive)")
	args = parser.parse_args(argv)

	config = normalize_config(args.config)
	if config is None:
		print_fail(f"Invalid config '{args.config}'. Valid: Debug, Release, Profile")
		return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
						   detail=f"invalid config: {args.config}")

	devenv = find_vs2026()
	if devenv is None:
		print_fail("Visual Studio 2026 not found")
		return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
						   detail="VS2026 not found")

	root = repo_root()
	sln = root / "z1engine.sln"
	if not sln.exists():
		print_fail(f"Solution not found: {sln}")
		print_info("Run 'python dev/z1.py generate' first.")
		return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
						   detail="z1engine.sln not found")

	timer = Timer()
	print_run(f"compile --config {config}")

	# Log file: dev/logs/compile_<config>_<timestamp>.log
	log_dir = root / "dev" / "logs"
	timestamp = time.strftime("%Y%m%d_%H%M%S")
	log_path = log_dir / f"compile_{config}_{timestamp}.log"

	print_info(f"Invoking devenv.com z1engine.sln /Build \"{config}|x64\"")
	print_info(f"Build log: {log_path}")

	rc, stdout, stderr = run_subprocess(
		[devenv, str(sln), "/Build", f"{config}|x64"],
		cwd=str(root),
		timeout=600,
		stream=True,
		log_file=log_path,
	)

	output = stdout + stderr
	errors = _RE_ERROR.findall(output)
	warnings = _RE_WARNING.findall(output)

	for filepath, line, msg in errors:
		print_fail(f"{filepath}:{line}: {msg.strip()}")

	for filepath, line, msg in warnings:
		print_warn(f"{filepath}:{line}: {msg.strip()}")

	elapsed = timer.elapsed()
	n_err = len(errors)
	n_warn = len(warnings)

	if rc == 0 and n_err == 0:
		print_ok(f"compile completed ({n_err} errors, {n_warn} warnings, {elapsed})")
		return make_result("ok", "compile", errors=n_err, warnings=n_warn, elapsed=elapsed)
	else:
		print_fail(f"compile failed ({n_err} errors, {n_warn} warnings, {elapsed})")
		return make_result("fail", "compile", exit_code=EXIT_BUILD_ERROR,
						   errors=n_err, warnings=n_warn, elapsed=elapsed)
