# [AI-GENERATED] This file was generated by an AI agent.
"""compile -- Build the solution via platform-appropriate build tool."""

import argparse
import os
import re
import sys
import time
from pathlib import Path
from commands._common import (
	EXIT_BUILD_ERROR, EXIT_CONFIG_ERROR, Timer, find_ccache, find_vs2026, find_make,
	make_result, normalize_config, print_fail, print_info, print_ok,
	print_run, print_warn, repo_root, run_subprocess, is_macos, is_windows,
)

# MSBuild error/warning patterns
_RE_ERROR_MSVC = re.compile(r"^(.*?)\((\d+)\):\s*error\s+\w+:\s*(.+)$", re.MULTILINE)
_RE_WARNING_MSVC = re.compile(r"^(.*?)\((\d+)\):\s*warning\s+\w+:\s*(.+)$", re.MULTILINE)
# GCC/Clang error/warning patterns
_RE_ERROR_CLANG = re.compile(r"^(.*?):(\d+):\d+:\s*error:\s*(.+)$", re.MULTILINE)
_RE_WARNING_CLANG = re.compile(r"^(.*?):(\d+):\d+:\s*warning:\s*(.+)$", re.MULTILINE)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 compile",
		description="Build the z1engine solution.",
	)
	parser.add_argument("--config", default="Hybrid",
						help="Build configuration: Debug, Release, Profile, Hybrid (case-insensitive)")
	parser.add_argument("--jobs", default=None,
						help="Parallel jobs (macOS; default: logical CPU count)")
	parser.add_argument("--ccache", action="store_true",
						help="Force ccache for the macOS build (fails when ccache is not installed)")
	parser.add_argument("--no-ccache", action="store_true",
						help="Disable the automatic ccache usage on macOS")
	args = parser.parse_args(argv)

	config = normalize_config(args.config)
	if config is None:
		print_fail(f"Invalid config '{args.config}'. Valid: Debug, Release, Profile, Hybrid")
		return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
						   detail=f"invalid config: {args.config}")

	jobs = None
	if args.jobs is not None:
		try:
			jobs = int(args.jobs)
		except (TypeError, ValueError):
			jobs = 0
		if jobs <= 0:
			print_fail(f"Invalid jobs value '{args.jobs}'. Expected a positive integer.")
			return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
							   detail=f"invalid jobs: {args.jobs}")
	if args.ccache and args.no_ccache:
		print_fail("--ccache and --no-ccache are mutually exclusive")
		return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
						   detail="ccache flags conflict")

	root = repo_root()
	timer = Timer()
	print_run(f"compile --config {config}")

	if is_macos():
		# macOS: use make
		make = find_make()
		if make is None:
			print_fail("make not found (install Xcode Command Line Tools: xcode-select --install)")
			return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
							   detail="make not found")

		if jobs is None:
			jobs = os.cpu_count() or 4
		print_info(f"jobs: {jobs}")

		ccache = None if args.no_ccache else find_ccache()
		if args.ccache and ccache is None:
			print_fail("ccache not found (install with: brew install ccache)")
			return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
							   detail="ccache not installed")

		env = None
		if ccache:
			# pch_defines/time_macros are required for the runtime precompiled header
			env = {"CC": f"{ccache} clang", "CXX": f"{ccache} clang++",
				   "CCACHE_SLOPPINESS": "pch_defines,time_macros"}
			print_info(f"ccache: enabled ({ccache})")
		else:
			print_info("ccache: not used")

		rc, stdout, stderr = run_subprocess(
			[make, f"config={config.lower()}", f"-j{jobs}", "game"],
			cwd=str(root),
			timeout=600,
			stream=True,
			env=env,
		)

		output = stdout + stderr
		errors = _RE_ERROR_CLANG.findall(output)
		warnings = _RE_WARNING_CLANG.findall(output)
	elif is_windows():
		# Windows: use devenv.com
		devenv = find_vs2026()
		if devenv is None:
			print_fail("Visual Studio 2026 not found")
			return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
							   detail="VS2026 not found")

		sln = root / "z1engine.sln"
		if not sln.exists():
			print_fail(f"Solution not found: {sln}")
			print_info("Run 'python dev/z1.py generate' first.")
			return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
							   detail="z1engine.sln not found")

		rc, stdout, stderr = run_subprocess(
			[devenv, str(sln), "/Build", f"{config}|x64"],
			cwd=str(root),
			timeout=600,
			stream=True,
		)

		output = stdout + stderr
		errors = _RE_ERROR_MSVC.findall(output)
		warnings = _RE_WARNING_MSVC.findall(output)
	else:
		print_fail(f"Unsupported platform: {sys.platform}")
		return make_result("fail", "compile", exit_code=EXIT_CONFIG_ERROR,
						   detail=f"unsupported platform: {sys.platform}")

	elapsed = timer.elapsed()
	n_err = len(errors)
	n_warn = len(warnings)

	# on macOS, report what the build actually used (jobs / cache mode)
	extra = {}
	if is_macos():
		extra = {"jobs": jobs, "ccache": bool(ccache)}

	if rc == 0 and n_err == 0:
		print_ok(f"compile completed ({n_err} errors, {n_warn} warnings, {elapsed})")
		return make_result("ok", "compile", errors=n_err, warnings=n_warn, elapsed=elapsed, **extra)
	else:
		print_fail(f"compile failed ({n_err} errors, {n_warn} warnings, {elapsed})")
		return make_result("fail", "compile", exit_code=EXIT_BUILD_ERROR,
						   errors=n_err, warnings=n_warn, elapsed=elapsed, **extra)
