# [AI-GENERATED] This file was generated by an AI agent.
"""dcv -- Full develop-compile-verify loop orchestrator."""

import argparse
import json
import sys
from commands._common import (
	EXIT_BUILD_ERROR, Timer, make_result, print_fail, print_info, print_ok,
	print_run, print_skip, repo_root, run_subprocess,
)

def _git_changed_files(root):
	"""Return list of changed file paths relative to repo root using git diff."""
	rc, stdout, _ = run_subprocess(
		["git", "diff", "--name-only", "HEAD"],
		cwd=str(root),
	)
	if rc != 0:
		# Fallback: also try unstaged
		rc2, stdout2, _ = run_subprocess(
			["git", "diff", "--name-only"],
			cwd=str(root),
		)
		stdout = stdout2 if rc2 == 0 else ""
	# Also include untracked
	rc3, stdout3, _ = run_subprocess(
		["git", "ls-files", "--others", "--exclude-standard"],
		cwd=str(root),
	)
	if rc3 == 0:
		stdout = stdout + "\n" + stdout3
	return [f.strip() for f in stdout.strip().splitlines() if f.strip()]

def _detect_steps(changed_files):
	"""Based on changed files, determine which steps to enable."""
	steps = {
		"generate": False,
		"compile": True,   # always
		"format": True,    # always
		"validate-shaders": False,
		"test": False,
		"smoke": False,
	}
	for f in changed_files:
		fl = f.lower().replace("\\", "/")
		if fl.endswith(".lua"):
			steps["generate"] = True
		if fl.endswith(".glsl"):
			steps["validate-shaders"] = True
		if "engine/runtime/" in fl or "engine/bakery/" in fl or "engine/test/" in fl:
			steps["test"] = True
	return steps

def _run_step(step_name, step_argv):
	"""Import and run a step module. Returns (status_str, result_dict)."""
	module_map = {
		"generate": "commands.generate",
		"compile": "commands.compile",
		"format": "commands.format_cmd",
		"validate-shaders": "commands.validate_shaders",
		"test": "commands.test",
		"smoke": "commands.smoke",
	}
	import importlib
	mod = importlib.import_module(module_map[step_name])
	# Capture the RESULT line by temporarily redirecting
	import io
	old_stdout = sys.stdout
	sys.stdout = captured = io.StringIO()
	try:
		exit_code = mod.main(step_argv)
	finally:
		sys.stdout = old_stdout

	output = captured.getvalue()
	# Print the captured output (so it's visible)
	print(output, end="")

	# Parse the RESULT line
	result_data = {}
	for line in output.strip().splitlines():
		if line.startswith("RESULT: "):
			try:
				result_data = json.loads(line[8:])
			except json.JSONDecodeError:
				pass

	status = result_data.get("status", "fail" if exit_code != 0 else "ok")
	return status, result_data

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 dcv",
		description="Full develop-compile-verify loop.",
	)
	parser.add_argument("--auto", action="store_true",
						help="Auto-detect which steps to run based on git diff")
	parser.add_argument("--generate", action="store_true",
						help="Force run generate step")
	parser.add_argument("--shaders", action="store_true",
						help="Force run shader validation step")
	parser.add_argument("--test", action="store_true",
						help="Force run test step")
	parser.add_argument("--smoke", action="store_true",
						help="Force run smoke test step")
	parser.add_argument("--config", default="Debug",
						help="Build config (default: Debug)")
	parser.add_argument("--all", action="store_true",
						help="Run all steps (generate, compile, format, shaders, test, smoke)")
	args = parser.parse_args(argv)

	root = repo_root()
	timer = Timer()
	print_run("dcv")

	# Determine which steps to run
	if args.all:
		steps = {k: True for k in ["generate", "compile", "format", "validate-shaders", "test", "smoke"]}
	elif args.auto:
		changed = _git_changed_files(root)
		print_info(f"Auto-detected {len(changed)} changed file(s)")
		steps = _detect_steps(changed)
	else:
		steps = {
			"generate": args.generate,
			"compile": True,
			"format": True,
			"validate-shaders": args.shaders,
			"test": args.test,
			"smoke": args.smoke,
		}

	# Force flags override
	if args.generate:
		steps["generate"] = True
	if args.shaders:
		steps["validate-shaders"] = True
	if args.test:
		steps["test"] = True
	if args.smoke:
		steps["smoke"] = True

	step_order = ["generate", "compile", "format", "validate-shaders", "test", "smoke"]
	step_results = {}
	overall_status = "ok"

	for step_name in step_order:
		if not steps.get(step_name, False):
			reason_map = {
				"generate": "no .lua changes",
				"validate-shaders": "no .glsl changes",
				"test": "no engine code changes",
				"smoke": "not requested",
			}
			reason = reason_map.get(step_name, "not enabled")
			print_skip(f"{step_name} ({reason})")
			step_results[step_name] = "skip"
			continue

		step_argv = []
		if step_name in ("compile", "validate-shaders", "test", "smoke"):
			step_argv = ["--config", args.config]

		status, _ = _run_step(step_name, step_argv)
		step_results[step_name] = status

		if status == "fail":
			overall_status = "fail"
			print_fail(f"DCV stopped at {step_name}")
			break

	elapsed = timer.elapsed()

	if overall_status == "ok":
		print_ok(f"DCV completed ({elapsed})")
	else:
		print_fail(f"DCV failed ({elapsed})")

	return make_result(overall_status, "dcv", steps=step_results, elapsed=elapsed)
