# [AI-GENERATED] This file was generated by an AI agent.
"""format -- Format source code (tabs, trailing whitespace, CRLF, ASCII check).

Absorbs logic from utils/format_code.py into the unified dev-scripts CLI.
"""

import argparse
import os
from pathlib import Path
from commands._common import (
	EXIT_VALIDATION_ERROR, Timer, make_result, print_fail, print_info,
	print_ok, print_run, print_warn, repo_root,
)

EXTENSIONS = {".h", ".cpp", ".glsl", ".py"}
SCAN_DIRS = [
	"engine/runtime",
	"engine/content",
	"engine/editor",
	"engine/game",
	"engine/test",
	"engine/tool",
]

def _convert_to_tabs(line):
	"""Convert leading spaces to tabs (tab width 4)."""
	i = 0
	while i < len(line) and line[i] in " \t":
		i += 1
	if i == 0:
		return line
	leading = line[:i]
	content = line[i:]
	expanded = leading.expandtabs(4)
	tabs = len(expanded) // 4
	remaining = len(expanded) % 4
	return "\t" * tabs + " " * remaining + content

def _process_file(filepath, dry_run):
	"""Process a single file. Returns (modified: bool, non_ascii_lines: list)."""
	try:
		with open(filepath, "rb") as f:
			content_bytes = f.read()
	except OSError:
		return False, []

	# Decode
	try:
		content = content_bytes.decode("utf-8")
	except UnicodeDecodeError:
		try:
			content = content_bytes.decode("latin-1")
			print_warn(f"Decoded as latin-1: {filepath}")
		except Exception:
			print_fail(f"Could not decode: {filepath}")
			return False, []

	lines = content.splitlines()
	new_lines = []
	non_ascii = []

	for i, line in enumerate(lines, 1):
		# ASCII check
		if not all(ord(c) < 128 for c in line):
			non_ascii.append(i)
		# Trailing whitespace
		current = line.rstrip()
		# Tabs
		current = _convert_to_tabs(current)
		new_lines.append(current)

	# CRLF
	if not new_lines:
		new_content = ""
	else:
		new_content = "\r\n".join(new_lines) + "\r\n"

	new_bytes = new_content.encode("utf-8")
	modified = (content_bytes != new_bytes)

	if modified:
		if not dry_run:
			with open(filepath, "wb") as f:
				f.write(new_bytes)

	return modified, non_ascii

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 format",
		description="Format source code: tabs, trailing whitespace, CRLF, ASCII check.",
	)
	parser.add_argument("--dry-run", action="store_true",
						help="Report changes without modifying files")
	args = parser.parse_args(argv)

	root = repo_root()
	timer = Timer()
	mode = "--dry-run" if args.dry_run else ""
	print_run(f"format {mode}".strip())

	files_fixed = 0
	files_scanned = 0
	non_ascii_total = 0

	for rel_dir in SCAN_DIRS:
		scan_dir = root / rel_dir
		if not scan_dir.exists():
			continue
		for dirpath, _, filenames in os.walk(scan_dir):
			for fname in filenames:
				if Path(fname).suffix not in EXTENSIONS:
					continue
				fpath = os.path.join(dirpath, fname)
				files_scanned += 1
				modified, non_ascii = _process_file(fpath, args.dry_run)
				if modified:
					files_fixed += 1
					print_info(f"Fixed: {os.path.relpath(fpath, root)}")
				for line_no in non_ascii:
					non_ascii_total += 1
					print_warn(f"Non-ASCII: {os.path.relpath(fpath, root)}:{line_no}")

	elapsed = timer.elapsed()

	if files_fixed == 0:
		print_ok(f"format completed -- all {files_scanned} files clean ({elapsed})")
	else:
		print_ok(f"format completed -- {files_fixed} files fixed of {files_scanned} scanned ({elapsed})")

	status = "warn" if non_ascii_total > 0 else "ok"
	return make_result(status, "format", files_fixed=files_fixed,
					   files_scanned=files_scanned, non_ascii=non_ascii_total,
					   elapsed=elapsed)
