# [AI-GENERATED] This file was generated by an AI agent.
"""gen-pybinds -- Regenerate Python bindings from reflected C++ types."""

import argparse
import os
import sys
from pathlib import Path
from commands._common import (
	EXIT_CONFIG_ERROR, Timer, make_result, print_fail, print_ok, print_run,
	repo_root, run_subprocess,
)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 gen-pybinds",
		description="Regenerate Python bindings (py_engine.gen.cpp + z1.pyi) from reflected C++ types.",
	)
	parser.add_argument("--check", action="store_true",
						help="Check for staleness (exit 2 if generated files differ)")
	parser.parse_args(argv)

	root = repo_root()
	gen_script = root / "utils" / "gen_pybinds.py"

	if not gen_script.exists():
		print_fail(f"gen_pybinds.py not found at {gen_script}")
		return make_result("fail", "gen-pybinds", exit_code=EXIT_CONFIG_ERROR,
						   detail="gen_pybinds.py not found")

	timer = Timer()
	print_run("gen-pybinds")

	# Run the generator script
	rc, stdout, stderr = run_subprocess(
		[sys.executable, str(gen_script)],
		cwd=str(root),
	)

	output = stdout + stderr
	if output.strip():
		for line in output.strip().splitlines():
			print(f"  {line}")

	elapsed = timer.elapsed()

	if rc == 0:
		print_ok(f"Python bindings generated ({elapsed})")
		return make_result("ok", "gen-pybinds", elapsed=elapsed)
	else:
		print_fail(f"gen_pybinds failed (exit {rc}, {elapsed})")
		return make_result("fail", "gen-pybinds", exit_code=rc,
						   elapsed=elapsed, detail=stderr)
