# [AI-GENERATED] This file was generated by an AI agent.
"""generate -- Regenerate project files from premake5."""

import argparse
from commands._common import (
	EXIT_CONFIG_ERROR, Timer, make_result, print_fail, print_ok, print_run,
	repo_root, run_subprocess, get_premake5_path, is_macos,
)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 generate",
		description="Regenerate Visual Studio project files using premake5.",
	)
	parser.parse_args(argv)

	root = repo_root()
	premake = get_premake5_path()

	if not premake:
		print_fail("premake5 not found")
		print("  Install via Homebrew: brew install premake")
		print("  Or place the binary at utils/premake/premake5")
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   detail="premake5 not found")

	timer = Timer()
	print_run("generate")

	if is_macos():
		rc, stdout, stderr = run_subprocess(
			[str(premake), "gmake"],
			cwd=str(root),
		)
	else:
		rc, stdout, stderr = run_subprocess(
			[str(premake), "vs2022", "--vs2026"],
			cwd=str(root),
		)

	output = stdout + stderr
	if output.strip():
		for line in output.strip().splitlines():
			print(f"  {line}")

	elapsed = timer.elapsed()

	if rc == 0:
		print_ok(f"Project files generated ({elapsed})")
		return make_result("ok", "generate", elapsed=elapsed)
	else:
		print_fail(f"premake5 failed (exit {rc}, {elapsed})")
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   elapsed=elapsed, detail=f"premake5 exit {rc}")
