# [AI-GENERATED] This file was generated by an AI agent.
"""generate -- Regenerate project files from premake5."""

import argparse
import shutil

from commands._common import (
	EXIT_CONFIG_ERROR, Timer, make_result, print_fail, print_info, print_ok,
	print_run, print_warn, repo_root, run_subprocess, get_premake5_path, is_macos,
	check_python,
)

def _generated_probing_state(root):
	"""Probing state baked into the current project files, or None if not generated yet."""
	if is_macos():
		project_file = root / "engine" / "runtime" / "Makefile"
	else:
		projects = sorted((root / "engine" / "runtime").glob("*.vcxproj"))
		project_file = projects[0] if projects else None
	if project_file is None or not project_file.exists():
		return None
	return "ENABLE_PROBING" in project_file.read_text(errors="ignore")

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 generate",
		description="Regenerate Visual Studio project files using premake5.",
	)
	parser.add_argument("--probing", action="store_true",
						help="Enable the frame prober (ENABLE_PROBING) in Hybrid builds (regenerate required)")
	parser.add_argument("--full-symbols", action="store_true",
						help="macOS: compile Hybrid/Profile with full -g instead of line-table debug info")
	args = parser.parse_args(argv)

	# Precheck: verify Python environment before generating
	py_ok, py_msg = check_python()
	if not py_ok:
		print_fail(py_msg)
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   detail="python environment not ready")

	root = repo_root()
	premake = get_premake5_path()

	if not premake:
		print_fail("premake5 not found")
		print("  Install via Homebrew: brew install premake")
		print("  Or place the binary at utils/premake/premake5")
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   detail="premake5 not found")

	timer = Timer()
	print_run("generate --probing" if args.probing else "generate")
	print_info("[INFO] probing enabled: ENABLE_PROBING is defined for Hybrid builds"
			   if args.probing else
			   "[INFO] probing disabled: builds are probe-free (pass --probing to enable)")
	if args.full_symbols:
		print_info("[INFO] full symbols: macOS Hybrid/Profile compile with -g instead of line tables")

	# Switching the flag changes what the sources must be compiled with, but object files do not
	# depend on the generated projects: drop the stale Hybrid objects so the next build is correct.
	previous_state = _generated_probing_state(root)
	if previous_state is not None and previous_state != args.probing:
		stale_dir = root / "engine" / "intermediate" / "Hybrid"
		if stale_dir.exists():
			shutil.rmtree(stale_dir, ignore_errors=True)
		print_warn("probing state changed ({} -> {}): removed stale Hybrid objects, "
				   "the next Hybrid build recompiles everything".format(
					   "on" if previous_state else "off",
					   "on" if args.probing else "off"))

	premake_command = ["gmake"] if is_macos() else ["vs2022", "--vs2026"]
	if args.probing:
		premake_command.append("--probing")
	if args.full_symbols:
		premake_command.append("--full-symbols")

	rc, stdout, stderr = run_subprocess(
		[str(premake)] + premake_command,
		cwd=str(root),
	)

	output = stdout + stderr
	if output.strip():
		for line in output.strip().splitlines():
			print(f"  {line}")

	elapsed = timer.elapsed()

	if rc == 0:
		print_ok(f"Project files generated ({elapsed})")
		return make_result("ok", "generate", elapsed=elapsed, probing=args.probing)
	else:
		print_fail(f"premake5 failed (exit {rc}, {elapsed})")
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   elapsed=elapsed, probing=args.probing, detail=f"premake5 exit {rc}")
