# [AI-GENERATED] This file was generated by an AI agent.
"""generate -- Regenerate VS project files from premake5."""

import argparse
from commands._common import (
	EXIT_CONFIG_ERROR, Timer, make_result, print_fail, print_ok, print_run,
	repo_root, run_subprocess,
)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 generate",
		description="Regenerate Visual Studio project files using premake5.",
	)
	parser.parse_args(argv)

	root = repo_root()
	premake = root / "utils" / "premake" / "premake5.exe"

	if not premake.exists():
		print_fail(f"premake5 not found at {premake}")
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   detail="premake5.exe not found")

	timer = Timer()
	print_run("generate")

	rc, stdout, stderr = run_subprocess(
		[str(premake), "vs2022", "--vs2026"],
		cwd=str(root),
	)

	output = stdout + stderr
	if output.strip():
		for line in output.strip().splitlines():
			print(f"  {line}")

	elapsed = timer.elapsed()

	if rc == 0:
		print_ok(f"Project files generated ({elapsed})")
		return make_result("ok", "generate", elapsed=elapsed)
	else:
		print_fail(f"premake5 failed (exit {rc}, {elapsed})")
		return make_result("fail", "generate", exit_code=EXIT_CONFIG_ERROR,
						   elapsed=elapsed, detail=f"premake5 exit {rc}")
