# [AI-GENERATED] This file was generated by an AI agent.
"""release -- Package release folder."""

import argparse
import shutil
from pathlib import Path
from commands._common import (
	EXIT_CONFIG_ERROR, EXIT_RUNTIME_ERROR, Timer, make_result, print_fail,
	print_info, print_ok, print_run, repo_root,
	get_executable_extension, get_shared_lib_extension, is_windows,
)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 release",
		description="Package a release folder with binaries and content.",
	)
	parser.parse_args(argv)

	root = repo_root()
	release_dir = root / "release"
	timer = Timer()
	print_run("release")

	# Clean existing release
	if release_dir.exists():
		print_info("Deleting existing release folder")
		shutil.rmtree(release_dir)

	release_dir.mkdir(parents=True)
	engine_dir = release_dir / "engine"
	engine_dir.mkdir()

	# Copy content directories
	copies = [
		(root / "engine" / "content", engine_dir / "content"),
		(root / "engine" / "config", engine_dir / "config"),
	]
	for src, dst in copies:
		if src.exists():
			shutil.copytree(src, dst)
			print_info(f"Copied {src.name}")
		else:
			print_info(f"Skipped {src.name} (not found)")

	# Copy binaries
	ext = get_executable_extension()
	dylib = get_shared_lib_extension()
	python_dir = root / "engine" / "3rdparty" / "python314"

	file_copies = [
		(root / "engine" / "bin" / "Release" / f"editor{ext}", release_dir / f"editor{ext}"),
		(root / "engine" / "bin" / "Release" / f"game{ext}", release_dir / f"game{ext}"),
	]
	if is_windows():
		file_copies += [
			(python_dir / "python314.dll", release_dir / "python314.dll"),
			(python_dir / "python314.zip", release_dir / "python314.zip"),
		]
	copied = 0
	missing = 0
	for src, dst in file_copies:
		if src.exists():
			shutil.copy2(src, dst)
			print_info(f"Copied {src.name}")
			copied += 1
		else:
			print_fail(f"Missing: {src}")
			missing += 1

	elapsed = timer.elapsed()

	if missing == 0:
		print_ok(f"release packaged ({elapsed})")
		return make_result("ok", "release", files_copied=copied, elapsed=elapsed)
	else:
		print_fail(f"release incomplete -- {missing} file(s) missing ({elapsed})")
		return make_result("warn", "release", files_copied=copied,
						   files_missing=missing, elapsed=elapsed)
