# [AI-GENERATED] This file was generated by an AI agent.
"""smoke -- Run editor smoke test (--frames)."""

import argparse
from pathlib import Path
from commands._common import (
	EXIT_CONFIG_ERROR, EXIT_RUNTIME_ERROR, Timer, make_result, print_fail,
	print_info, print_ok, print_run, repo_root, run_subprocess, normalize_config,
	get_executable_extension,
)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 smoke",
		description="Run editor smoke test (start and render a few frames).",
	)
	parser.add_argument("--frames", type=int, default=1,
						help="Number of frames to render (default: 1)")
	parser.add_argument("--config", default="Hybrid",
						help="Build config (default: Hybrid)")
	parser.add_argument("--scene", default="",
						help="Scene asset path to load (e.g. scene/ParticleDemo)")
	args = parser.parse_args(argv)

	config = normalize_config(args.config) or "Hybrid"
	root = repo_root()
	ext = get_executable_extension()

	# Try game, then editor
	candidates = [
		root / "engine" / "bin" / config / f"game{ext}",
		root / "engine" / "bin" / config / f"editor{ext}",
	]
	exe = None
	for c in candidates:
		if c.exists():
			exe = c
			break

	if exe is None:
		print_fail(f"No game{ext} or editor{ext} found")
		print_info("Build the solution first: python dev/z1.py compile")
		return make_result("fail", "smoke", exit_code=EXIT_CONFIG_ERROR,
						   detail="executable not found")

	timer = Timer()
	print_run(f"smoke --frames {args.frames}")
	print_info(f"Using: {exe}")

	rc, stdout, stderr = run_subprocess(
		[str(exe), f"--frames={args.frames}"] + ([f"--scene={args.scene}"] if args.scene else []),
		cwd=str(root),
		timeout=30,
	)

	elapsed = timer.elapsed()

	if rc == 0:
		# Echo any diagnostic lines printed by the engine (e.g. CSM shadow stats)
		diag_lines = [l for l in stdout.splitlines() if l.strip()]
		for line in diag_lines:
			print_info(f"  {line}")
		print_ok(f"Editor started and rendered {args.frames} frame(s) ({elapsed})")
		return make_result("ok", "smoke", frames=args.frames, elapsed=elapsed)
	else:
		snippet = stderr.strip().splitlines()[:3] if stderr.strip() else ["(no stderr)"]
		for line in snippet:
			print_info(f"  {line}")
		print_fail(f"Editor crashed (exit {rc}, {elapsed})")
		return make_result("fail", "smoke", exit_code=EXIT_RUNTIME_ERROR,
						   frames=args.frames, elapsed=elapsed,
						   detail=f"exit code {rc}")
