# [AI-GENERATED] This file was generated by an AI agent.
"""test -- Discover and run test executables."""

import argparse
import fnmatch
import os
from pathlib import Path
from commands._common import (
	EXIT_CONFIG_ERROR, EXIT_RUNTIME_ERROR, Timer, make_result, print_fail,
	print_info, print_ok, print_run, print_skip, repo_root, run_subprocess,
	normalize_config, get_executable_extension, is_macos,
)

def _discover_tests(test_dir, pattern=None, names=None):
	"""Find test executables in the given directory."""
	if not test_dir.exists():
		return []
	ext = get_executable_extension()
	if is_macos():
		# On macOS, find executables by checking file permissions
		tests = sorted([
			f for f in test_dir.iterdir()
			if f.is_file() and f.name.startswith("test_")
			and os.access(f, os.X_OK)
		])
	else:
		tests = sorted(test_dir.glob(f"test_*{ext}"))
	if names:
		norm = set()
		for n in names:
			ns = n.strip()
			if not ns:
				continue
			norm.add(ns)
			if ns.endswith(ext):
				norm.add(ns[:-len(ext)])
			else:
				norm.add(ns + ext)
		tests = [t for t in tests if t.name in norm or t.stem in norm]
	if pattern:
		tests = [t for t in tests if fnmatch.fnmatch(t.name, pattern)]
	return tests

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 test",
		description="Discover and run test executables.",
	)
	parser.add_argument("--filter", default=None,
						help="Glob pattern to filter test executables (e.g., 'test_render*')")
	parser.add_argument("--name", action="append", default=[],
						help="Exact test name (stem or filename), repeatable")
	parser.add_argument("--config", default="Hybrid",
						help="Build config (default: Hybrid)")
	args = parser.parse_args(argv)

	config = normalize_config(args.config) or "Hybrid"
	root = repo_root()
	test_dir = root / "engine" / "bin" / "test" / config

	if not test_dir.exists():
		# Try without config subdirectory
		test_dir = root / "engine" / "bin" / "test"

	timer = Timer()
	filter_display = f" --filter {args.filter}" if args.filter else ""
	if args.name:
		filter_display += " --name " + ",".join(args.name)
	print_run(f"test{filter_display}")

	tests = _discover_tests(test_dir, args.filter, args.name)

	if not tests:
		print_skip(f"No test executables found in {test_dir}")
		return make_result("ok", "test", passed=0, failed=0, total=0,
						   elapsed=timer.elapsed(), detail="no tests found")

	print_info(f"Found {len(tests)} test(s) in {test_dir}")

	passed = 0
	failed = 0
	failures = []

	for test_exe in tests:
		name = test_exe.stem
		rc, stdout, stderr = run_subprocess(
			[str(test_exe)],
			cwd=str(root),
			timeout=60,
		)
		if rc == 0:
			print_ok(name)
			passed += 1
		else:
			print_fail(f"{name}: exit code {rc}")
			if stderr.strip():
				for line in stderr.strip().splitlines()[:5]:
					print_info(f"  {line}")
			failed += 1
			failures.append(name)

	elapsed = timer.elapsed()
	total = passed + failed

	if failed == 0:
		print_ok(f"test completed ({passed} passed, {elapsed})")
		return make_result("ok", "test", passed=passed, failed=failed, total=total,
						   elapsed=elapsed)
	else:
		print_fail(f"test failed ({failed} failed, {passed} passed, {elapsed})")
		return make_result("fail", "test", exit_code=EXIT_RUNTIME_ERROR,
						   passed=passed, failed=failed, total=total,
						   failures=failures, elapsed=elapsed)
