# [AI-GENERATED] This file was generated by an AI agent.
"""validate_shaders -- Validate all GLSL shaders."""

import argparse
from pathlib import Path
from commands._common import (
	EXIT_CONFIG_ERROR, EXIT_VALIDATION_ERROR, Timer, make_result, print_fail,
	print_ok, print_run, print_info, repo_root, run_subprocess, normalize_config,
	get_executable_extension,
)

def main(argv=None):
	parser = argparse.ArgumentParser(
		prog="z1 validate-shaders",
		description="Validate all GLSL shaders using shader_validator.",
	)
	parser.add_argument("--config", default="Debug",
						help="Build config to find shader_validator (default: Debug)")
	args = parser.parse_args(argv)

	config = normalize_config(args.config) or "Debug"
	root = repo_root()
	ext = get_executable_extension()

	# Try multiple known paths for shader_validator
	candidates = [
		root / "engine" / "bin" / config / f"shader_validator{ext}",
		root / "engine" / "bin" / f"shader_validator{ext}",
	]

	validator = None
	for c in candidates:
		if c.exists():
			validator = c
			break

	if validator is None:
		print_fail(f"shader_validator{ext} not found")
		print_info(f"Searched: {', '.join(str(c) for c in candidates)}")
		print_info("Build the solution first: python dev/z1.py compile")
		return make_result("fail", "validate-shaders", exit_code=EXIT_CONFIG_ERROR,
						   detail=f"shader_validator{ext} not found")

	timer = Timer()
	print_run("validate-shaders")
	print_info(f"Using: {validator}")

	rc, stdout, stderr = run_subprocess(
		[str(validator)],
		cwd=str(root),
		timeout=120,
	)

	output = (stdout + stderr).strip()
	passed = 0
	failed = 0

	if output:
		for line in output.splitlines():
			line_s = line.strip()
			# Heuristic: lines with "error" or "fail" indicate failures
			if "error" in line_s.lower() or "fail" in line_s.lower():
				print_fail(line_s)
				failed += 1
			elif "ok" in line_s.lower() or "pass" in line_s.lower() or "success" in line_s.lower():
				print_ok(line_s)
				passed += 1
			else:
				print_info(line_s)

	elapsed = timer.elapsed()

	if rc == 0 and failed == 0:
		print_ok(f"validate-shaders completed ({passed} passed, {elapsed})")
		return make_result("ok", "validate-shaders", passed=passed, failed=failed,
						   elapsed=elapsed)
	else:
		print_fail(f"validate-shaders failed ({failed} failed, {passed} passed, {elapsed})")
		return make_result("fail", "validate-shaders", exit_code=EXIT_VALIDATION_ERROR,
						   passed=passed, failed=failed, elapsed=elapsed)
