// This file is automatically generated by utils/gen_pybinds.py
// Do not modify this file directly.

#include "pch.h"
#include "z1engine.h"
#include "asset/material.h"
#include "render/data_types.h"
#include "render/global.h"
#include "scene/component/animation.h"
#include "scene/component/base.h"
#include "scene/component/camera.h"
#include "scene/component/collider.h"
#include "scene/component/light.h"
#include "scene/component/mesh.h"
#include "scene/component/particle.h"
#include "scene/component/physics.h"
#include "scene/component/postprocess_volume.h"
#include "scene/component/sky_light.h"
#include "scene/component/sprite.h"

#include "pybind11/embed.h"
#include "pybind11/stl.h"
namespace py = pybind11;
using namespace z1;

void bind_generated(py::module& m, py::class_<Entity, std::shared_ptr<Entity>>& entity_cls) {
	// Bind Enums
	py::enum_<AOMode>(m, "AOMode")
		.value("SSAO", AOMode::SSAO)
		.value("GTAO", AOMode::GTAO)
		.export_values();

	py::enum_<ColliderShape>(m, "ColliderShape")
		.value("Sphere", ColliderShape::Sphere)
		.value("Box", ColliderShape::Box)
		.value("Capsule", ColliderShape::Capsule)
		.export_values();

	py::enum_<DataType>(m, "DataType")
		.value("None", DataType::None)
		.value("Float", DataType::Float)
		.value("Float2", DataType::Float2)
		.value("Float3", DataType::Float3)
		.value("Float4", DataType::Float4)
		.value("Int", DataType::Int)
		.value("Int2", DataType::Int2)
		.value("Int3", DataType::Int3)
		.value("Int4", DataType::Int4)
		.value("Mat3", DataType::Mat3)
		.value("Mat4", DataType::Mat4)
		.value("Bool", DataType::Bool)
		.value("Sampler2D", DataType::Sampler2D)
		.value("Sampler2DArray", DataType::Sampler2DArray)
		.value("SamplerCube", DataType::SamplerCube)
		.export_values();

	py::enum_<EmitterShape>(m, "EmitterShape")
		.value("Point", EmitterShape::Point)
		.value("Sphere", EmitterShape::Sphere)
		.value("Box", EmitterShape::Box)
		.value("Cone", EmitterShape::Cone)
		.export_values();

	py::enum_<LightType>(m, "LightType")
		.value("Directional", LightType::Directional)
		.value("Point", LightType::Point)
		.value("Spot", LightType::Spot)
		.export_values();

	py::enum_<ParticleBlendMode>(m, "ParticleBlendMode")
		.value("Alpha", ParticleBlendMode::Alpha)
		.value("Additive", ParticleBlendMode::Additive)
		.value("Soft", ParticleBlendMode::Soft)
		.export_values();

	py::enum_<PhysicsMode>(m, "PhysicsMode")
		.value("Static", PhysicsMode::Static)
		.value("Kinematic", PhysicsMode::Kinematic)
		.value("Dynamic", PhysicsMode::Dynamic)
		.export_values();

	py::enum_<RenderMode>(m, "RenderMode")
		.value("Forward", RenderMode::Forward)
		.value("Deferred", RenderMode::Deferred)
		.export_values();

	// Generated Bindings
	py::class_<AnimationComponent>(m, "Animation")
		.def_readwrite("animation_asset", &AnimationComponent::animation_asset)
		.def_readwrite("current_time", &AnimationComponent::current_time)
		.def_readwrite("speed", &AnimationComponent::speed)
		.def_readwrite("loop", &AnimationComponent::loop)
		.def_readwrite("playing", &AnimationComponent::playing);

	py::class_<CameraComponent>(m, "Camera")
		.def(py::init<>())
		.def_readwrite("is_perspective", &CameraComponent::m_is_perspective)
		.def_readwrite("near", &CameraComponent::m_near)
		.def_readwrite("far", &CameraComponent::m_far)
		.def_readwrite("aspect", &CameraComponent::m_aspect)
		.def_readwrite("use_fixed_aspect", &CameraComponent::m_use_fixed_aspect)
		.def_readwrite("is_primary", &CameraComponent::m_is_primary);

	py::class_<ColliderComponent>(m, "Collider")
		.def(py::init<>())
		.def_readwrite("shape", &ColliderComponent::m_shape)
		.def_readwrite("half_extents", &ColliderComponent::m_half_extents);

	py::class_<GlobalSettings>(m, "GlobalSettings")
		.def(py::init<>())
		.def_readwrite("sun_direction", &GlobalSettings::sun_direction)
		.def_readwrite("sun_color", &GlobalSettings::sun_color)
		.def_readwrite("sun_intensity", &GlobalSettings::sun_intensity)
		.def_readwrite("sun_ambient_color", &GlobalSettings::sun_ambient_color)
		.def_readwrite("sun_ambient_intensity", &GlobalSettings::sun_ambient_intensity)
		.def_readwrite("taa_enabled", &GlobalSettings::taa_enabled)
		.def_readwrite("taa_blend", &GlobalSettings::taa_blend)
		.def_readwrite("taa_variance_scale", &GlobalSettings::taa_variance_scale)
		.def_readwrite("taa_clip_gamma", &GlobalSettings::taa_clip_gamma)
		.def_readwrite("taa_sharpen_enabled", &GlobalSettings::taa_sharpen_enabled)
		.def_readwrite("taa_sharpen_strength", &GlobalSettings::taa_sharpen_strength)
		.def_readwrite("taa_animated", &GlobalSettings::taa_animated)
		.def_readwrite("pp_exposure", &GlobalSettings::pp_exposure)
		.def_readwrite("pp_gamma", &GlobalSettings::pp_gamma)
		.def_readwrite("pp_tint", &GlobalSettings::pp_tint)
		.def_readwrite("pp_bloom_enabled", &GlobalSettings::pp_bloom_enabled)
		.def_readwrite("pp_bloom_threshold", &GlobalSettings::pp_bloom_threshold)
		.def_readwrite("pp_bloom_intensity", &GlobalSettings::pp_bloom_intensity)
		.def_readwrite("pp_bloom_knee", &GlobalSettings::pp_bloom_knee)
		.def_readwrite("sm_near", &GlobalSettings::sm_near)
		.def_readwrite("sm_far", &GlobalSettings::sm_far)
		.def_readwrite("sm_ortho_size", &GlobalSettings::sm_ortho_size)
		.def_readwrite("ao_enabled", &GlobalSettings::ao_enabled)
		.def_readwrite("ao_type", &GlobalSettings::ao_type)
		.def_readwrite("ao_radius", &GlobalSettings::ao_radius)
		.def_readwrite("ao_intensity", &GlobalSettings::ao_intensity)
		.def_readwrite("ao_power", &GlobalSettings::ao_power)
		.def_readwrite("ao_bias", &GlobalSettings::ao_bias)
		.def_readwrite("ao_blur_enabled", &GlobalSettings::ao_blur_enabled)
		.def_readwrite("ao_blur_strength", &GlobalSettings::ao_blur_strength)
		.def_readwrite("anim_enabled", &GlobalSettings::anim_enabled)
		.def_readwrite("script_enabled", &GlobalSettings::script_enabled)
		.def_readwrite("render_mode", &GlobalSettings::render_mode);

	py::class_<LightComponent>(m, "Light")
		.def(py::init<>())
		.def_readwrite("type", &LightComponent::m_type)
		.def_readwrite("color", &LightComponent::m_color)
		.def_readwrite("intensity", &LightComponent::m_intensity)
		.def_readwrite("range", &LightComponent::m_range)
		.def_readwrite("inner_cone", &LightComponent::m_inner_cone)
		.def_readwrite("outer_cone", &LightComponent::m_outer_cone)
		.def_readwrite("cast_shadow", &LightComponent::m_cast_shadow);

	py::class_<Material>(m, "Material")
		.def_readwrite("flags", &Material::m_flags)
		.def_readwrite("shader_guid", &Material::m_shader_guid)
		.def_readwrite("variables", &Material::m_variables);

	py::class_<MaterialInstance>(m, "MaterialInstance")
		.def_readwrite("material", &MaterialInstance::m_material)
		.def_readwrite("override_variables", &MaterialInstance::m_override_variables)
		.def_readwrite("override_flags", &MaterialInstance::m_override_flags)
		.def_readwrite("override_mask", &MaterialInstance::m_override_mask);

	py::class_<ParticleComponent>(m, "Particle")
		.def(py::init<>())
		.def_readwrite("max_particles", &ParticleComponent::m_max_particles)
		.def_readwrite("emission_rate", &ParticleComponent::m_emission_rate)
		.def_readwrite("burst_count", &ParticleComponent::m_burst_count)
		.def_readwrite("lifetime", &ParticleComponent::m_lifetime)
		.def_readwrite("initial_speed", &ParticleComponent::m_initial_speed)
		.def_readwrite("direction", &ParticleComponent::m_direction)
		.def_readwrite("direction_spread", &ParticleComponent::m_direction_spread)
		.def_readwrite("gravity", &ParticleComponent::m_gravity)
		.def_readwrite("damping", &ParticleComponent::m_damping)
		.def_readwrite("initial_size", &ParticleComponent::m_initial_size)
		.def_readwrite("size_over_life", &ParticleComponent::m_size_over_life)
		.def_readwrite("initial_color", &ParticleComponent::m_initial_color)
		.def_readwrite("end_color", &ParticleComponent::m_end_color)
		.def_readwrite("texture", &ParticleComponent::m_texture)
		.def_readwrite("blend_mode", &ParticleComponent::m_blend_mode)
		.def_readwrite("emitter_shape", &ParticleComponent::m_emitter_shape)
		.def_readwrite("shape_radius", &ParticleComponent::m_shape_radius)
		.def_readwrite("shape_extents", &ParticleComponent::m_shape_extents)
		.def_readwrite("world_space", &ParticleComponent::m_world_space)
		.def_readwrite("loop", &ParticleComponent::m_loop)
		.def_readwrite("playing", &ParticleComponent::m_playing)
		.def_readwrite("sort_by_depth", &ParticleComponent::m_sort_by_depth)
		.def_readwrite("receive_shadows", &ParticleComponent::m_receive_shadows)
		.def_readwrite("cast_shadows", &ParticleComponent::m_cast_shadows)
		.def_readwrite("initial_rotation", &ParticleComponent::m_initial_rotation)
		.def_readwrite("rotation_speed", &ParticleComponent::m_rotation_speed);

	py::class_<PhysicsComponent>(m, "Physics")
		.def(py::init<>())
		.def_readwrite("mode", &PhysicsComponent::m_mode)
		.def_readwrite("mass", &PhysicsComponent::m_mass)
		.def_readwrite("use_gravity", &PhysicsComponent::m_use_gravity)
		.def_readwrite("linear_damping", &PhysicsComponent::m_linear_damping);

	py::class_<PostprocessVolumeComponent>(m, "PostprocessVolume")
		.def_readwrite("enabled", &PostprocessVolumeComponent::enabled)
		.def_readwrite("is_global", &PostprocessVolumeComponent::is_global)
		.def_readwrite("priority", &PostprocessVolumeComponent::priority)
		.def_readwrite("blend_distance", &PostprocessVolumeComponent::blend_distance)
		.def_readwrite("override_exposure", &PostprocessVolumeComponent::override_exposure)
		.def_readwrite("exposure", &PostprocessVolumeComponent::exposure)
		.def_readwrite("override_gamma", &PostprocessVolumeComponent::override_gamma)
		.def_readwrite("gamma", &PostprocessVolumeComponent::gamma)
		.def_readwrite("override_tint", &PostprocessVolumeComponent::override_tint)
		.def_readwrite("tint", &PostprocessVolumeComponent::tint)
		.def_readwrite("override_bloom_enabled", &PostprocessVolumeComponent::override_bloom_enabled)
		.def_readwrite("bloom_enabled", &PostprocessVolumeComponent::bloom_enabled)
		.def_readwrite("override_bloom_threshold", &PostprocessVolumeComponent::override_bloom_threshold)
		.def_readwrite("bloom_threshold", &PostprocessVolumeComponent::bloom_threshold)
		.def_readwrite("override_bloom_intensity", &PostprocessVolumeComponent::override_bloom_intensity)
		.def_readwrite("bloom_intensity", &PostprocessVolumeComponent::bloom_intensity)
		.def_readwrite("override_bloom_knee", &PostprocessVolumeComponent::override_bloom_knee)
		.def_readwrite("bloom_knee", &PostprocessVolumeComponent::bloom_knee);

	py::class_<SkeletalMeshComponent>(m, "SkeletalMesh")
		.def_readwrite("mesh", &SkeletalMeshComponent::m_mesh)
		.def_readwrite("skeleton", &SkeletalMeshComponent::m_skeleton)
		.def_readwrite("override_materials", &SkeletalMeshComponent::m_override_materials);

	py::class_<SkyLightComponent>(m, "SkyLight")
		.def(py::init<>())
		.def_readwrite("texture", &SkyLightComponent::m_texture)
		.def_readwrite("rotation", &SkyLightComponent::m_rotation)
		.def_readwrite("intensity", &SkyLightComponent::m_intensity)
		.def_readwrite("mip_level", &SkyLightComponent::m_mip_level);

	py::class_<SpriteComponent>(m, "Sprite")
		.def(py::init<>())
		.def_readwrite("color", &SpriteComponent::m_color)
		.def_readwrite("texture", &SpriteComponent::m_texture)
		.def_readwrite("tiling_scale", &SpriteComponent::m_tiling_scale)
		.def_readwrite("tiling_offset", &SpriteComponent::m_tiling_offset)
		.def_readwrite("texcoords", &SpriteComponent::m_texcoords)
		.def_readwrite("extras", &SpriteComponent::m_extras);

	py::class_<StaticMeshComponent>(m, "StaticMesh")
		.def_readwrite("mesh", &StaticMeshComponent::m_mesh)
		.def_readwrite("override_materials", &StaticMeshComponent::m_override_materials);

	py::class_<TagComponent>(m, "Tag")
		.def(py::init<>())
		.def_readwrite("tag", &TagComponent::m_tag)
		.def_readwrite("id", &TagComponent::m_id);

	py::class_<TransformComponent>(m, "Transform")
		.def(py::init<>())
		.def_readwrite("location", &TransformComponent::m_location)
		.def_readwrite("rotation", &TransformComponent::m_rotation)
		.def_readwrite("scale", &TransformComponent::m_scale);

	// Entity component properties
	entity_cls.def_property_readonly("animation", [](Entity& e) -> AnimationComponent* {
		if (e.has_component<AnimationComponent>()) {
			return &e.get_component<AnimationComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("camera", [](Entity& e) -> CameraComponent* {
		if (e.has_component<CameraComponent>()) {
			return &e.get_component<CameraComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("collider", [](Entity& e) -> ColliderComponent* {
		if (e.has_component<ColliderComponent>()) {
			return &e.get_component<ColliderComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("light", [](Entity& e) -> LightComponent* {
		if (e.has_component<LightComponent>()) {
			return &e.get_component<LightComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("particle", [](Entity& e) -> ParticleComponent* {
		if (e.has_component<ParticleComponent>()) {
			return &e.get_component<ParticleComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("physics", [](Entity& e) -> PhysicsComponent* {
		if (e.has_component<PhysicsComponent>()) {
			return &e.get_component<PhysicsComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("postprocess_volume", [](Entity& e) -> PostprocessVolumeComponent* {
		if (e.has_component<PostprocessVolumeComponent>()) {
			return &e.get_component<PostprocessVolumeComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("skeletal_mesh", [](Entity& e) -> SkeletalMeshComponent* {
		if (e.has_component<SkeletalMeshComponent>()) {
			return &e.get_component<SkeletalMeshComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("sky_light", [](Entity& e) -> SkyLightComponent* {
		if (e.has_component<SkyLightComponent>()) {
			return &e.get_component<SkyLightComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("sprite", [](Entity& e) -> SpriteComponent* {
		if (e.has_component<SpriteComponent>()) {
			return &e.get_component<SpriteComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("static_mesh", [](Entity& e) -> StaticMeshComponent* {
		if (e.has_component<StaticMeshComponent>()) {
			return &e.get_component<StaticMeshComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("tag", [](Entity& e) -> TagComponent* {
		if (e.has_component<TagComponent>()) {
			return &e.get_component<TagComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);
	entity_cls.def_property_readonly("transform", [](Entity& e) -> TransformComponent* {
		if (e.has_component<TransformComponent>()) {
			return &e.get_component<TransformComponent>();
		}
		return nullptr;
	}, py::return_value_policy::reference);

	// Allow access to GlobalSettings via z1.globals or z1.global
	m.def("__getattr__", [](const std::string &name) -> py::object {
		if (name == "globals" || name == "global") {
			return py::cast(z1::g_runtime_context.m_global.get(), py::return_value_policy::reference);
		}
		if (name == "scene") {
			return py::cast(z1::g_runtime_context.m_scene.get(), py::return_value_policy::reference);
		}
		throw py::attribute_error("module 'z1' has no attribute '" + name + "'");
	});
}
