// This file is automatically generated by utils/gen_pybinds.py
// Do not modify this file directly.

#include "pch.h"
#include "z1engine.h"
#include "render/global.h"
#include "scene/component/animation.h"
#include "scene/component/base.h"
#include "scene/component/camera.h"
#include "scene/component/light.h"
#include "scene/component/mesh.h"
#include "scene/component/sky_light.h"
#include "scene/component/sprite.h"

#include "pybind11/embed.h"
namespace py = pybind11;

using namespace z1;

void ForceLinkPythonEngine() {}

static void log_info_py(std::string const& msg) { CLIENT_INFO(msg); }
static void log_warn_py(std::string const& msg) { CLIENT_WARN(msg); }
static void log_error_py(std::string const& msg) { CLIENT_ERROR(msg); }

// This macro "creates" the 'z1' module inside the Python VM
PYBIND11_EMBEDDED_MODULE(z1, m) {
	CORE_INFO("Initializing z1 Python module");
	m.doc() = "z1 Engine API";
	m.def("log_info", &log_info_py);
	m.def("log_warn", &log_warn_py);
	m.def("log_error", &log_error_py);

	// Bind GLM
	py::class_<glm::vec2>(m, "Vec2")
		.def(py::init<float, float>())
		.def(py::init<>())
		.def_readwrite("x", &glm::vec2::x)
		.def_readwrite("y", &glm::vec2::y)
		.def("__repr__", [](const glm::vec2& v) {
			return "Vec2(" + std::to_string(v.x) + ", " + std::to_string(v.y) + ")";
		});

	py::class_<glm::vec3>(m, "Vec3")
		.def(py::init<float, float, float>())
		.def(py::init<>())
		.def_readwrite("x", &glm::vec3::x)
		.def_readwrite("y", &glm::vec3::y)
		.def_readwrite("z", &glm::vec3::z)
		.def("__repr__", [](const glm::vec3& v) {
			return "Vec3(" + std::to_string(v.x) + ", " + std::to_string(v.y) + ", " + std::to_string(v.z) + ")";
		});

	py::class_<glm::vec4>(m, "Vec4")
		.def(py::init<float, float, float, float>())
		.def(py::init<>())
		.def_readwrite("x", &glm::vec4::x)
		.def_readwrite("y", &glm::vec4::y)
		.def_readwrite("z", &glm::vec4::z)
		.def_readwrite("w", &glm::vec4::w)
		.def("__repr__", [](const glm::vec4& v) {
			return "Vec4(" + std::to_string(v.x) + ", " + std::to_string(v.y) + ", " + std::to_string(v.z) + ", " + std::to_string(v.w) + ")";
		});

	// Generated Bindings
	py::class_<AnimationComponent>(m, "Animation")
		.def_readwrite("animation_asset", &AnimationComponent::animation_asset)
		.def_readwrite("current_time", &AnimationComponent::current_time)
		.def_readwrite("speed", &AnimationComponent::speed)
		.def_readwrite("loop", &AnimationComponent::loop)
		.def_readwrite("playing", &AnimationComponent::playing);

	py::class_<CameraComponent>(m, "Camera")
		.def(py::init<>())
		.def_readwrite("is_perspective", &CameraComponent::m_is_perspective)
		.def_readwrite("near", &CameraComponent::m_near)
		.def_readwrite("far", &CameraComponent::m_far)
		.def_readwrite("aspect", &CameraComponent::m_aspect)
		.def_readwrite("use_fixed_aspect", &CameraComponent::m_use_fixed_aspect)
		.def_readwrite("is_primary", &CameraComponent::m_is_primary);

	py::class_<GlobalSettings>(m, "GlobalSettings")
		.def(py::init<>())
		.def_readwrite("sun_direction", &GlobalSettings::sun_direction)
		.def_readwrite("sun_color", &GlobalSettings::sun_color)
		.def_readwrite("sun_intensity", &GlobalSettings::sun_intensity)
		.def_readwrite("sun_ambient_color", &GlobalSettings::sun_ambient_color)
		.def_readwrite("sun_ambient_intensity", &GlobalSettings::sun_ambient_intensity)
		.def_readwrite("taa_enabled", &GlobalSettings::taa_enabled)
		.def_readwrite("taa_blend", &GlobalSettings::taa_blend)
		.def_readwrite("taa_animated", &GlobalSettings::taa_animated)
		.def_readwrite("pp_exposure", &GlobalSettings::pp_exposure)
		.def_readwrite("pp_gamma", &GlobalSettings::pp_gamma)
		.def_readwrite("pp_tint", &GlobalSettings::pp_tint)
		.def_readwrite("pp_bloom_enabled", &GlobalSettings::pp_bloom_enabled)
		.def_readwrite("pp_bloom_threshold", &GlobalSettings::pp_bloom_threshold)
		.def_readwrite("pp_bloom_intensity", &GlobalSettings::pp_bloom_intensity)
		.def_readwrite("pp_bloom_knee", &GlobalSettings::pp_bloom_knee)
		.def_readwrite("sm_near", &GlobalSettings::sm_near)
		.def_readwrite("sm_far", &GlobalSettings::sm_far)
		.def_readwrite("sm_ortho_size", &GlobalSettings::sm_ortho_size)
		.def_readwrite("anim_enabled", &GlobalSettings::anim_enabled);

	py::class_<LightComponent>(m, "Light")
		.def(py::init<>())
		.def_readwrite("type", &LightComponent::m_type)
		.def_readwrite("color", &LightComponent::m_color)
		.def_readwrite("intensity", &LightComponent::m_intensity)
		.def_readwrite("range", &LightComponent::m_range)
		.def_readwrite("inner_cone", &LightComponent::m_inner_cone)
		.def_readwrite("outer_cone", &LightComponent::m_outer_cone)
		.def_readwrite("cast_shadow", &LightComponent::m_cast_shadow);

	py::class_<SkeletalMeshComponent>(m, "SkeletalMesh");

	py::class_<SkyLightComponent>(m, "SkyLight")
		.def(py::init<>())
		.def_readwrite("texture", &SkyLightComponent::m_texture)
		.def_readwrite("rotation", &SkyLightComponent::m_rotation)
		.def_readwrite("intensity", &SkyLightComponent::m_intensity)
		.def_readwrite("mip_level", &SkyLightComponent::m_mip_level);

	py::class_<SpriteComponent>(m, "Sprite")
		.def(py::init<>())
		.def_readwrite("color", &SpriteComponent::m_color)
		.def_readwrite("tiling_scale", &SpriteComponent::m_tiling_scale)
		.def_readwrite("tiling_offset", &SpriteComponent::m_tiling_offset)
		.def_readwrite("texcoords", &SpriteComponent::m_texcoords);

	py::class_<StaticMeshComponent>(m, "StaticMesh");

	py::class_<TagComponent>(m, "Tag")
		.def(py::init<>())
		.def_readwrite("tag", &TagComponent::m_tag);

	py::class_<TransformComponent>(m, "Transform")
		.def(py::init<>())
		.def_readwrite("location", &TransformComponent::m_location)
		.def_readwrite("rotation", &TransformComponent::m_rotation)
		.def_readwrite("scale", &TransformComponent::m_scale);

	// Bind Entity
	py::class_<Entity, std::shared_ptr<Entity>>(m, "Entity")
		.def_property_readonly("animation", [](Entity& e) -> AnimationComponent* {
			if (e.has_component<AnimationComponent>()) {
				return &e.get_component<AnimationComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("camera", [](Entity& e) -> CameraComponent* {
			if (e.has_component<CameraComponent>()) {
				return &e.get_component<CameraComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("light", [](Entity& e) -> LightComponent* {
			if (e.has_component<LightComponent>()) {
				return &e.get_component<LightComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("skeletal_mesh", [](Entity& e) -> SkeletalMeshComponent* {
			if (e.has_component<SkeletalMeshComponent>()) {
				return &e.get_component<SkeletalMeshComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("sky_light", [](Entity& e) -> SkyLightComponent* {
			if (e.has_component<SkyLightComponent>()) {
				return &e.get_component<SkyLightComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("sprite", [](Entity& e) -> SpriteComponent* {
			if (e.has_component<SpriteComponent>()) {
				return &e.get_component<SpriteComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("static_mesh", [](Entity& e) -> StaticMeshComponent* {
			if (e.has_component<StaticMeshComponent>()) {
				return &e.get_component<StaticMeshComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("tag", [](Entity& e) -> TagComponent* {
			if (e.has_component<TagComponent>()) {
				return &e.get_component<TagComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def_property_readonly("transform", [](Entity& e) -> TransformComponent* {
			if (e.has_component<TransformComponent>()) {
				return &e.get_component<TransformComponent>();
			}
			return nullptr;
		}, py::return_value_policy::reference)
		.def("is_valid", &Entity::is_valid);

	// Helper class for Python to inherit from (mocking ScriptBase)
	struct PyScript {
		virtual void on_attach() {}
		virtual void on_update(float) {}
		virtual void on_detach() {}
		virtual ~PyScript() = default;
	};

	// Bind Script Base Class for Python to inherit
	py::class_<PyScript>(m, "Script")
		.def(py::init<>())
		.def("on_attach", &PyScript::on_attach)
		.def("on_update", &PyScript::on_update)
		.def("on_detach", &PyScript::on_detach);
}
