// [AI-GENERATED] This file was generated by an AI agent.
#pragma once

// the editor project has no precompiled header: provide the std headers that
// render/global.h relies on before including it
#include <functional>
#include <memory>
#include <string>
#include <vector>

#include "render/global.h"

// Editor-only graphics quality presets. Presets are a development convenience: they apply a
// curated set of global render settings that games configure themselves from script.
namespace z1 {

	enum class QualityPreset : int {
		Low = 0,
		Medium = 1,
		High = 2,
	};

	// Applies the preset to the given global settings; artistic values (AO radius/intensity,
	// exposure, sun parameters, ...) keep their current values.
	void apply_quality_preset(GlobalSettings& settings, QualityPreset preset);

	char const* quality_preset_name(QualityPreset preset);

}
