// [AI-GENERATED] This file was generated by an AI agent.
#include "quality_preset.h"

namespace z1 {

	void apply_quality_preset(GlobalSettings& settings, QualityPreset preset) {
		// settings shared by every preset: AO runs and is blurred
		settings.ao_enabled = true;
		settings.ao_blur_enabled = true;

		switch (preset) {
		case QualityPreset::Low:
			settings.taa_enabled = false;
			settings.taa_sharpen_enabled = false;
			settings.ao_resolution = AOResolution::Quarter;
			settings.pp_bloom_enabled = false;
			settings.ssr_enabled = false;
			settings.sm_resolution = ShadowResolution::Res1024;
			settings.sm_cascade_count = ShadowCascades::One;
			break;
		case QualityPreset::Medium:
			settings.taa_enabled = true;
			settings.taa_sharpen_enabled = false;
			settings.ao_resolution = AOResolution::Half;
			settings.pp_bloom_enabled = true;
			settings.sm_resolution = ShadowResolution::Res2048;
			settings.sm_cascade_count = ShadowCascades::Two;
			break;
		case QualityPreset::High:
		default:
			settings.taa_enabled = true;
			settings.taa_sharpen_enabled = true;
			settings.ao_resolution = AOResolution::Half;
			settings.pp_bloom_enabled = true;
			settings.ssr_enabled = true;
			settings.sm_resolution = ShadowResolution::Res2048;
			settings.sm_cascade_count = ShadowCascades::Four;
			break;
		}
	}

	char const* quality_preset_name(QualityPreset preset) {
		switch (preset) {
		case QualityPreset::Low:
			return "LOW";
		case QualityPreset::Medium:
			return "MEDIUM";
		case QualityPreset::High:
		default:
			return "HIGH";
		}
	}

}
