# [AI-GENERATED] This file was generated by an AI agent.

"""Generates engine/content meshes and textures procedurally.

Meshes are indexed (shared vertices, smooth shading on curved surfaces) and written as
BinaryFile assets; textures are LZ4-compressed RGBA8. Engine ids come from utils/z1_guid.py,
so every asset carries the deterministic id the engine derives at scan time.
"""

import argparse
import math
import os
import random
import struct
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import z1_guid

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = REPO_ROOT / "engine" / "content"
MESHES = ["cone", "cube", "cylinder", "plane", "sphere"]
TEXTURES = ["black", "checker", "grid", "magenta", "noise", "normal", "white"]

BINARY_FILE_MAGIC = 0x5A314246
BINARY_FILE_HEADER = struct.Struct("<IIQQ")
VERTEX_FLOATS = 18
VERTEX_STRIDE = VERTEX_FLOATS * 4

LZ4_MIN_MATCH = 4
LZ4_MAX_OFFSET = 65535
LZ4_LAST_LITERALS = 5
LZ4_MATCH_LIMIT = 12

# solid textures keep the size of the assets they replace
TEXTURE_SIZES = {"black": 32, "magenta": 32, "normal": 1, "white": 32}
TEXTURE_NEAREST = {"normal"}


# ---------------------------------------------------------------------------
# LZ4 block format (the engine stores textures as LZ4_compress_default output)
# ---------------------------------------------------------------------------
def _emit_length(out, value):
	while value >= 255:
		out.append(255)
		value -= 255
	out.append(value)


def _emit_sequence(out, literals, offset, match_length):
	literal_count = len(literals)
	match_nibble = min(max(match_length - LZ4_MIN_MATCH, 0), 15) if offset else 0
	out.append((min(literal_count, 15) << 4) | match_nibble)
	if literal_count >= 15:
		_emit_length(out, literal_count - 15)
	out += literals
	if offset:
		out.append(offset & 0xFF)
		out.append((offset >> 8) & 0xFF)
		if match_length - LZ4_MIN_MATCH >= 15:
			_emit_length(out, match_length - LZ4_MIN_MATCH - 15)


def lz4_compress_block(data):
	data = bytes(data)
	length = len(data)
	out = bytearray()

	# below 13 bytes the format allows literals only
	if length < LZ4_MATCH_LIMIT + 1:
		_emit_sequence(out, data, 0, 0)
		return bytes(out)

	table = {}
	anchor = 0
	index = 0
	match_limit = length - LZ4_MATCH_LIMIT
	while index < match_limit:
		key = data[index:index + LZ4_MIN_MATCH]
		candidate = table.get(key)
		table[key] = index
		if candidate is None or index - candidate > LZ4_MAX_OFFSET:
			index += 1
			continue

		# extend the match, but never into the last five bytes
		match_length = LZ4_MIN_MATCH
		limit = length - LZ4_LAST_LITERALS - index
		match_end = index + LZ4_MIN_MATCH
		candidate_end = candidate + LZ4_MIN_MATCH
		while match_length < limit and data[match_end] == data[candidate_end]:
			match_end += 1
			candidate_end += 1
			match_length += 1

		_emit_sequence(out, data[anchor:index], index - candidate, match_length)
		index += match_length
		anchor = index

	_emit_sequence(out, data[anchor:], 0, 0)
	return bytes(out)


def lz4_decompress_block(data, expected_size):
	out = bytearray()
	index = 0
	size = len(data)
	while index < size:
		token = data[index]
		index += 1
		literal_count = token >> 4
		if literal_count == 15:
			while data[index] == 255:
				literal_count += 255
				index += 1
			literal_count += data[index]
			index += 1
		out += data[index:index + literal_count]
		index += literal_count
		if index >= size:
			break
		offset = data[index] | (data[index + 1] << 8)
		index += 2
		if offset == 0 or offset > len(out):
			raise ValueError(f"invalid match offset {offset}")
		match_length = token & 0x0F
		if match_length == 15:
			while data[index] == 255:
				match_length += 255
				index += 1
			match_length += data[index]
			index += 1
		match_length += LZ4_MIN_MATCH
		start = len(out) - offset
		for step in range(match_length):
			out.append(out[start + step])
	if len(out) != expected_size:
		raise ValueError(f"decoded {len(out)} bytes, expected {expected_size}")
	return bytes(out)


# ---------------------------------------------------------------------------
# mesh building (indexed triangles, outward winding fixed per triangle)
# ---------------------------------------------------------------------------
def _cross(a, b):
	return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _dot(a, b):
	return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _normalize(v):
	length = math.sqrt(_dot(v, v))
	if length == 0.0:
		return (0.0, 0.0, 0.0)
	return (v[0] / length, v[1] / length, v[2] / length)


class MeshBuilder:
	"""Collects vertices and triangles; flips winding so faces point away from the reference."""

	def __init__(self):
		self.vertices = []
		self.triangles = []

	def add_vertex(self, position, normal, uv):
		self.vertices.append((position, normal, uv))
		return len(self.vertices) - 1

	def add_triangle(self, i0, i1, i2, reference=None):
		p0 = self.vertices[i0][0]
		p1 = self.vertices[i1][0]
		p2 = self.vertices[i2][0]
		face = _normalize(_cross(
			(p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]),
			(p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2])))
		if reference is None:
			reference = _normalize((p0[0] + p1[0] + p2[0], p0[1] + p1[1] + p2[1], p0[2] + p1[2] + p2[2]))
		if _dot(face, reference) < 0.0:
			i0, i2 = i2, i0
		self.triangles.append((i0, i1, i2))

	def add_quad(self, i0, i1, i2, i3, reference=None):
		self.add_triangle(i0, i1, i2, reference)
		self.add_triangle(i0, i2, i3, reference)

	def indices(self):
		result = []
		for triangle in self.triangles:
			result.extend(triangle)
		return result


def build_cube():
	# unit cube [-1, 1]^3, one vertex per face corner for flat shading and box UVs
	builder = MeshBuilder()
	for axis in range(3):
		for sign in (1.0, -1.0):
			normal = [0.0, 0.0, 0.0]
			normal[axis] = sign
			helper = (1.0, 0.0, 0.0) if axis == 1 else (0.0, 1.0, 0.0)
			u = _normalize(_cross(helper, normal))
			v = _cross(normal, u)
			corners = [
				(normal[0] - u[0] - v[0], normal[1] - u[1] - v[1], normal[2] - u[2] - v[2]),
				(normal[0] + u[0] - v[0], normal[1] + u[1] - v[1], normal[2] + u[2] - v[2]),
				(normal[0] + u[0] + v[0], normal[1] + u[1] + v[1], normal[2] + u[2] + v[2]),
				(normal[0] - u[0] + v[0], normal[1] - u[1] + v[1], normal[2] - u[2] + v[2]),
			]
			uvs = [(0.0, 1.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)]
			base = [builder.add_vertex(corner, normal, uv) for corner, uv in zip(corners, uvs)]
			builder.add_quad(base[0], base[1], base[2], base[3], normal)
	return builder


def build_plane():
	# unit ground plane [-1, 1] on X/Z, facing +Y
	builder = MeshBuilder()
	normal = (0.0, 1.0, 0.0)
	corners = [(-1.0, 0.0, -1.0), (-1.0, 0.0, 1.0), (1.0, 0.0, 1.0), (1.0, 0.0, -1.0)]
	uvs = [(0.0, 1.0), (0.0, 0.0), (1.0, 0.0), (1.0, 1.0)]
	base = [builder.add_vertex(corner, normal, uv) for corner, uv in zip(corners, uvs)]
	builder.add_quad(base[0], base[1], base[2], base[3], normal)
	return builder


def build_sphere(segments, rings):
	# unit UV sphere with poles on Y, smooth normals
	builder = MeshBuilder()
	rows = []
	for ring in range(1, rings):
		theta = math.pi * ring / rings
		sin_theta, cos_theta = math.sin(theta), math.cos(theta)
		row = []
		for segment in range(segments):
			phi = 2.0 * math.pi * segment / segments
			position = (sin_theta * math.cos(phi), cos_theta, sin_theta * math.sin(phi))
			row.append(builder.add_vertex(position, position, (segment / segments, 1.0 - ring / rings)))
		rows.append(row)

	north = builder.add_vertex((0.0, 1.0, 0.0), (0.0, 1.0, 0.0), (0.5, 1.0))
	south = builder.add_vertex((0.0, -1.0, 0.0), (0.0, -1.0, 0.0), (0.5, 0.0))
	first, last = rows[0], rows[-1]
	for segment in range(segments):
		next_segment = (segment + 1) % segments
		builder.add_triangle(north, first[segment], first[next_segment])
		builder.add_triangle(south, last[segment], last[next_segment])
	for ring in range(len(rows) - 1):
		top, bottom = rows[ring], rows[ring + 1]
		for segment in range(segments):
			next_segment = (segment + 1) % segments
			builder.add_quad(top[segment], bottom[segment], bottom[next_segment], top[next_segment])
	return builder


def build_cone(segments):
	# unit cone: apex at +Y, base ring at -Y, smooth side normals and a flat cap
	builder = MeshBuilder()
	apex = builder.add_vertex((0.0, 1.0, 0.0), (0.0, 1.0, 0.0), (0.5, 1.0))
	side_ring = []
	cap_ring = []
	for segment in range(segments):
		phi = 2.0 * math.pi * segment / segments
		cos_phi, sin_phi = math.cos(phi), math.sin(phi)
		position = (cos_phi, -1.0, sin_phi)
		side_normal = _normalize((2.0 * cos_phi, 1.0, 2.0 * sin_phi))
		side_ring.append(builder.add_vertex(position, side_normal, (segment / segments, 0.0)))
		cap_ring.append(builder.add_vertex(position, (0.0, -1.0, 0.0), (0.5 + 0.5 * cos_phi, 0.5 - 0.5 * sin_phi)))
	center = builder.add_vertex((0.0, -1.0, 0.0), (0.0, -1.0, 0.0), (0.5, 0.5))
	for segment in range(segments):
		next_segment = (segment + 1) % segments
		builder.add_triangle(apex, side_ring[segment], side_ring[next_segment])
		builder.add_triangle(center, cap_ring[segment], cap_ring[next_segment])
	return builder


def build_cylinder(segments):
	# unit cylinder between y = -1 and y = 1, smooth sides and flat caps
	builder = MeshBuilder()
	top_side, bottom_side, top_cap, bottom_cap = [], [], [], []
	for segment in range(segments):
		phi = 2.0 * math.pi * segment / segments
		cos_phi, sin_phi = math.cos(phi), math.sin(phi)
		radial = (cos_phi, 0.0, sin_phi)
		top_side.append(builder.add_vertex((cos_phi, 1.0, sin_phi), radial, (segment / segments, 1.0)))
		bottom_side.append(builder.add_vertex((cos_phi, -1.0, sin_phi), radial, (segment / segments, 0.0)))
		top_cap.append(builder.add_vertex((cos_phi, 1.0, sin_phi), (0.0, 1.0, 0.0), (0.5 + 0.5 * cos_phi, 0.5 + 0.5 * sin_phi)))
		bottom_cap.append(builder.add_vertex((cos_phi, -1.0, sin_phi), (0.0, -1.0, 0.0), (0.5 + 0.5 * cos_phi, 0.5 - 0.5 * sin_phi)))
	top_center = builder.add_vertex((0.0, 1.0, 0.0), (0.0, 1.0, 0.0), (0.5, 0.5))
	bottom_center = builder.add_vertex((0.0, -1.0, 0.0), (0.0, -1.0, 0.0), (0.5, 0.5))
	for segment in range(segments):
		next_segment = (segment + 1) % segments
		builder.add_quad(top_side[segment], top_side[next_segment], bottom_side[next_segment], bottom_side[segment])
		builder.add_triangle(top_center, top_cap[segment], top_cap[next_segment])
		builder.add_triangle(bottom_center, bottom_cap[segment], bottom_cap[next_segment])
	return builder


# ---------------------------------------------------------------------------
# texture generators (RGBA8, tiles seamlessly with WrapMode Repeat)
# ---------------------------------------------------------------------------
def texture_solid(size, color):
	row = bytes(color) * size
	return row * size


def texture_checker(size, cells, light=(255, 255, 255, 255), dark=(64, 64, 64, 255)):
	cell_pixels = size // cells
	light_bytes, dark_bytes = bytes(light), bytes(dark)
	pixels = bytearray(size * size * 4)
	for y in range(size):
		row_even = ((y // cell_pixels) % 2) == 0
		offset = y * size * 4
		for x in range(size):
			cell_even = ((x // cell_pixels) % 2) == 0
			pixels[offset:offset + 4] = light_bytes if cell_even == row_even else dark_bytes
			offset += 4
	return bytes(pixels)


def texture_grid(size, cells, line_width=2, line=(48, 48, 48, 255), background=(224, 224, 224, 255)):
	cell_pixels = size // cells
	pixels = bytearray(size * size * 4)
	for y in range(size):
		on_horizontal = (y % cell_pixels) < line_width
		for x in range(size):
			on_vertical = (x % cell_pixels) < line_width
			color = line if (on_horizontal or on_vertical) else background
			offset = (y * size + x) * 4
			pixels[offset:offset + 4] = bytes(color)
	return bytes(pixels)


def _smoothstep(value):
	return value * value * (3.0 - 2.0 * value)


def _value_noise(size, cells, seed):
	rng = random.Random(seed)
	lattice = [[rng.random() for _ in range(cells)] for _ in range(cells)]
	values = [0.0] * (size * size)
	for y in range(size):
		sample_y = y / size * cells
		y0 = int(sample_y) % cells
		y1 = (y0 + 1) % cells
		fade_y = _smoothstep(sample_y - int(sample_y))
		for x in range(size):
			sample_x = x / size * cells
			x0 = int(sample_x) % cells
			x1 = (x0 + 1) % cells
			fade_x = _smoothstep(sample_x - int(sample_x))
			top = lattice[y0][x0] + (lattice[y0][x1] - lattice[y0][x0]) * fade_x
			bottom = lattice[y1][x0] + (lattice[y1][x1] - lattice[y1][x0]) * fade_x
			values[y * size + x] = top + (bottom - top) * fade_y
	return values


def texture_noise(size, cells, octaves, seed):
	accumulated = [0.0] * (size * size)
	amplitude = 1.0
	total = 0.0
	for octave in range(octaves):
		octave_cells = min(cells * (2 ** octave), size)
		octave_values = _value_noise(size, octave_cells, seed + octave)
		for index, value in enumerate(octave_values):
			accumulated[index] += value * amplitude
		total += amplitude
		amplitude *= 0.5
		if octave_cells >= size:
			break
	pixels = bytearray(size * size * 4)
	for index, value in enumerate(accumulated):
		shade = int(max(0.0, min(1.0, value / total)) * 255.0 + 0.5)
		offset = index * 4
		pixels[offset] = shade
		pixels[offset + 1] = shade
		pixels[offset + 2] = shade
		pixels[offset + 3] = 255
	return bytes(pixels)


# ---------------------------------------------------------------------------
# asset writers (BinaryFile meshes, LZ4 textures, deterministic engine ids)
# ---------------------------------------------------------------------------
def _format_scalar(value):
	return f"{value:.9g}"


def _format_vec3(value):
	return "[" + ", ".join(_format_scalar(component) for component in value) + "]"


def _to_float32(value):
	return struct.unpack("<f", struct.pack("<f", value))[0]


def write_mesh(name, builder, mesh_dir):
	stem = "SM_" + name.capitalize()
	indices = builder.indices()
	vertex_count = len(builder.vertices)

	# round every component through float32 so yaml bounds and binary data agree
	vertices = []
	for position, normal, uv in builder.vertices:
		values = [
			_to_float32(position[0]), _to_float32(position[1]), _to_float32(position[2]),
			_to_float32(normal[0]), _to_float32(normal[1]), _to_float32(normal[2]),
			_to_float32(uv[0]), _to_float32(uv[1]),
			0.0, 0.0,
			1.0, 0.0, 0.0, 0.0,
			1.0, 1.0, 1.0, 1.0,
		]
		vertices.append(tuple(values))

	bound_min = [min(vertex[axis] for vertex in vertices) for axis in range(3)]
	bound_max = [max(vertex[axis] for vertex in vertices) for axis in range(3)]

	payload = bytearray()
	for vertex in vertices:
		payload += struct.pack("<18f", *vertex)
	for index in indices:
		payload += struct.pack("<I", index)

	guid = z1_guid.guid_for("engine", f"mesh/{stem}")
	yaml_lines = [
		f"bound_min: {_format_vec3(bound_min)}",
		f"bound_max: {_format_vec3(bound_max)}",
		f"vertex_count: {vertex_count}",
		f"index_count: {len(indices)}",
		"primitives:",
		"  - index_start: 0",
		f"    index_count: {len(indices)}",
		f"    vertex_count: {vertex_count}",
		f"    bound_min: {_format_vec3(bound_min)}",
		f"    bound_max: {_format_vec3(bound_max)}",
		"    material: ~",
		"    has_indices: true",
		"    has_normal: true",
		"    has_tangent: false",
		"meta:",
		f"  guid: {guid}",
		"  type: static mesh",
		f"  path: mesh/{stem}",
		"  extra: ~",
	]
	yaml_text = "\r\n".join(yaml_lines) + "\r\n"

	mesh_dir.mkdir(parents=True, exist_ok=True)
	(mesh_dir / f"{stem}.yaml").write_bytes(yaml_text.encode("utf-8"))
	encoded = yaml_text.encode("utf-8")
	header = BINARY_FILE_HEADER.pack(BINARY_FILE_MAGIC, 1, len(encoded), len(payload))
	(mesh_dir / f"{stem}.bin").write_bytes(header + encoded + bytes(payload))
	return stem, vertex_count, len(indices)


def write_texture(name, size, pixels, texture_dir, sampler_mode):
	stem = "T_" + name
	guid = z1_guid.guid_for("engine", f"texture/{stem}")
	yaml_lines = [
		"meta:",
		f"  guid: {guid}",
		"  type: texture2d",
		f"  path: texture/{stem}",
		"  extra:",
		f"    sampler_mode: {sampler_mode}",
		"    wrap_mode: 0",
		"    hdr: false",
	]
	yaml_text = "\r\n".join(yaml_lines) + "\r\n"

	compressed = lz4_compress_block(pixels)
	texture_dir.mkdir(parents=True, exist_ok=True)
	(texture_dir / f"{stem}.yaml").write_bytes(yaml_text.encode("utf-8"))
	(texture_dir / f"{stem}.bin").write_bytes(struct.pack("<iii", size, size, len(compressed)) + compressed)
	return f"{stem}.bin"


# ---------------------------------------------------------------------------
# verification (re-reads what was written and decodes it)
# ---------------------------------------------------------------------------
def verify_mesh(path, expected_vertex_count, expected_index_count):
	raw = path.read_bytes()
	magic, version, yaml_size, data_size = BINARY_FILE_HEADER.unpack_from(raw, 0)
	offset = BINARY_FILE_HEADER.size
	if magic != BINARY_FILE_MAGIC or version != 1:
		raise ValueError(f"{path.name}: bad header")
	expected = expected_vertex_count * VERTEX_STRIDE + expected_index_count * 4
	if data_size != expected or offset + yaml_size + data_size != len(raw):
		raise ValueError(f"{path.name}: size mismatch ({data_size} != {expected})")

	positions = []
	for vertex in range(expected_vertex_count):
		positions.append(struct.unpack_from("<3f", raw, offset + yaml_size + vertex * VERTEX_STRIDE))

	indices_offset = offset + yaml_size + expected_vertex_count * VERTEX_STRIDE
	for triangle in range(expected_index_count // 3):
		i0, i1, i2 = struct.unpack_from("<3I", raw, indices_offset + triangle * 12)
		if max(i0, i1, i2) >= expected_vertex_count:
			raise ValueError(f"{path.name}: index out of range in triangle {triangle}")
		p0, p1, p2 = positions[i0], positions[i1], positions[i2]
		face = _cross(
			(p1[0] - p0[0], p1[1] - p0[1], p1[2] - p0[2]),
			(p2[0] - p0[0], p2[1] - p0[1], p2[2] - p0[2]))
		centroid = (
			(p0[0] + p1[0] + p2[0]) / 3.0,
			(p0[1] + p1[1] + p2[1]) / 3.0,
			(p0[2] + p1[2] + p2[2]) / 3.0)
		if _dot(face, centroid) < 0.0:
			raise ValueError(f"{path.name}: triangle {triangle} winds inward")


def verify_texture(path, size, expected_pixels):
	raw = path.read_bytes()
	width, height, compressed_size = struct.unpack_from("<iii", raw, 0)
	if width != size or height != size or 12 + compressed_size != len(raw):
		raise ValueError(f"{path.name}: size mismatch")
	decoded = lz4_decompress_block(raw[12:], size * size * 4)
	if decoded != expected_pixels:
		raise ValueError(f"{path.name}: pixel data mismatch")


def main():
	parser = argparse.ArgumentParser(
		description="Generate engine/content meshes and textures procedurally.")
	parser.add_argument("selectors", nargs="*", metavar="name",
		help="mesh:<name> or texture:<name> to regenerate (default: everything)")
	parser.add_argument("--content-dir", default=str(CONTENT_DIR),
		help="content root to write into (default: engine/content)")
	parser.add_argument("--segments", type=int, default=32, help="radial segments (cone, cylinder, sphere)")
	parser.add_argument("--rings", type=int, default=16, help="latitude rings (sphere)")
	parser.add_argument("--texture-size", type=int, default=256, help="size of the procedural textures")
	parser.add_argument("--checker-cells", type=int, default=8, help="checker squares per axis")
	parser.add_argument("--grid-cells", type=int, default=8, help="grid cells per axis")
	parser.add_argument("--noise-cells", type=int, default=4, help="noise lattice size at octave 0")
	parser.add_argument("--noise-octaves", type=int, default=4, help="noise octaves")
	parser.add_argument("--noise-seed", type=int, default=1337, help="noise seed")
	parser.add_argument("--list", action="store_true", help="list generatable assets and exit")
	args = parser.parse_args()

	if args.list:
		print("meshes:   " + ", ".join(MESHES))
		print("textures: " + ", ".join(TEXTURES))
		return 0

	meshes = list(MESHES)
	textures = list(TEXTURES)
	if args.selectors:
		meshes, textures = [], []
		for selector in args.selectors:
			kind, _, name = selector.partition(":")
			if not name:
				name, kind = kind, "mesh" if kind in MESHES else "texture"
			if kind == "mesh" and name in MESHES:
				meshes.append(name)
			elif kind == "texture" and name in TEXTURES:
				textures.append(name)
			else:
				print(f"[ERROR] unknown selector: {selector}")
				return 1

	content_dir = Path(args.content_dir)
	mesh_dir = content_dir / "mesh"
	texture_dir = content_dir / "texture"

	builders = {
		"cone": lambda: build_cone(args.segments),
		"cube": build_cube,
		"cylinder": lambda: build_cylinder(args.segments),
		"plane": build_plane,
		"sphere": lambda: build_sphere(args.segments, args.rings),
	}
	generators = {
		"black": lambda size: texture_solid(size, (0, 0, 0, 255)),
		"checker": lambda size: texture_checker(size, args.checker_cells),
		"grid": lambda size: texture_grid(size, args.grid_cells),
		"magenta": lambda size: texture_solid(size, (255, 0, 255, 255)),
		"noise": lambda size: texture_noise(size, args.noise_cells, args.noise_octaves, args.noise_seed),
		"normal": lambda size: texture_solid(size, (127, 127, 255, 255)),
		"white": lambda size: texture_solid(size, (255, 255, 255, 255)),
	}

	written = 0
	for name in meshes:
		stem, vertex_count, index_count = write_mesh(name, builders[name](), mesh_dir)
		verify_mesh(mesh_dir / f"{stem}.bin", vertex_count, index_count)
		print(f"[OK] mesh    mesh/{stem} ({vertex_count} vertices, {index_count // 3} triangles)")
		written += 2

	for name in textures:
		size = TEXTURE_SIZES.get(name, args.texture_size)
		pixels = generators[name](size)
		file_name = write_texture(name, size, pixels, texture_dir, 1 if name in TEXTURE_NEAREST else 0)
		verify_texture(texture_dir / file_name, size, pixels)
		print(f"[OK] texture texture/T_{name} ({size}x{size})")
		written += 2

	print(f"[OK] generated {written} file(s) in {content_dir}")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
