# [AI-GENERATED] This file was generated by an AI agent.

"""Migrates stored guids and references to the deterministic path-derived ids.

Pass 1 builds an old -> new map from yaml sidecars, the yaml embedded in .bin assets, and
mesh primitive/meta pairs; pass 2 rewrites yaml, .bin and script/shader references.
Idempotent: once migrated, a second run changes nothing. Path-style references are never
rewritten.
"""

import argparse
import os
import re
import struct
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import z1_guid

REPO_ROOT = Path(__file__).resolve().parent.parent
ROOTS = [
	("", REPO_ROOT / "content"),
	("engine", REPO_ROOT / "engine" / "content"),
]
EXTRA_FILES = [REPO_ROOT / "editor_settings.yaml"]
GUID_TOKEN = re.compile(r"\A(?:[0-9a-fA-F]{32}|[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12})\Z")
ANY_GUID = re.compile(r"[0-9a-fA-F]{32}|[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}")
MATERIAL_LINE = re.compile(r"^\s*material:\s*(\S+)\s*$", re.MULTILINE)
BINARY_FILE_MAGIC = 0x5A314246
BINARY_FILE_HEADER = struct.Struct("<IIQQ")


def unquote(text):
	if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
		return text[1:-1]
	return text


def read_meta(lines):
	"""Returns (path_value, guid_line_index) of the file's meta block, or (None, None)."""
	meta_start = None
	for index, line in enumerate(lines):
		if line.rstrip("\r\n") == "meta:":
			meta_start = index
			break
	if meta_start is None:
		return None, None

	path_value = None
	guid_line = None
	for index in range(meta_start + 1, len(lines)):
		line = lines[index]
		if line.strip() and not line[:1].isspace():
			break
		key, _, value = line.strip().partition(":")
		key = key.strip()
		if key == "path":
			path_value = unquote(value.strip())
		elif key == "guid":
			guid_line = index
	return path_value, guid_line


def split_newline(line):
	if line.endswith("\r\n"):
		return line[:-2], "\r\n"
	if line.endswith("\n"):
		return line[:-1], "\n"
	return line, ""


def read_text(path):
	raw = path.read_bytes()
	bom = raw.startswith(b"\xef\xbb\xbf")
	return raw.decode("utf-8-sig" if bom else "utf-8"), bom


def write_text(path, text, bom):
	data = text.encode("utf-8")
	if bom:
		data = b"\xef\xbb\xbf" + data
	path.write_bytes(data)


def read_bin_sections(path):
	"""Returns (embedded yaml text, payload bytes) of a BinaryFile asset, or (None, None)."""
	raw = path.read_bytes()
	if len(raw) < BINARY_FILE_HEADER.size:
		return None, None
	magic, version, yaml_size, data_size = BINARY_FILE_HEADER.unpack_from(raw, 0)
	if magic != BINARY_FILE_MAGIC or version != 1 or BINARY_FILE_HEADER.size + yaml_size + data_size > len(raw):
		return None, None
	offset = BINARY_FILE_HEADER.size
	return raw[offset:offset + yaml_size].decode("utf-8", errors="replace"), raw[offset + yaml_size:]


def primitive_materials(text):
	return [unquote(match) for match in MATERIAL_LINE.findall(text)]


def build_map():
	mapping = {}
	derived = set()
	for root_name, root_dir in ROOTS:
		if not root_dir.is_dir():
			print(f"[WARN] missing root: {root_dir}")
			continue
		for path in sorted(root_dir.rglob("*.yaml")):
			text, _ = read_text(path)
			lines = text.splitlines(keepends=True)
			meta_path, guid_line = read_meta(lines)
			if meta_path is None or guid_line is None:
				continue
			record_mapping(root_name, meta_path, lines[guid_line], mapping, derived)

		# .bin assets embed a yaml copy whose meta and primitive material ids can still be stale
		for path in sorted(root_dir.rglob("*.bin")):
			embedded, _ = read_bin_sections(path)
			if embedded is None:
				continue
			lines = embedded.splitlines(keepends=True)
			meta_path, guid_line = read_meta(lines)
			if meta_path is not None and guid_line is not None:
				record_mapping(root_name, meta_path, lines[guid_line], mapping, derived)
			sidecar = path.with_suffix(".yaml")
			if sidecar.is_file():
				# sidecar and embedded yaml describe the same primitives, so ids pair up
				side_text, _ = read_text(sidecar)
				pair_materials(embedded, side_text, mapping)

	print(f"[INFO] stored ids mapped: {len(mapping)}")
	return mapping, derived


def record_mapping(root_name, meta_path, guid_line, mapping, derived):
	new_guid = z1_guid.guid_for(root_name, meta_path)
	derived.add(new_guid)
	old_guid = unquote(guid_line.strip().partition(":")[2].strip())
	if GUID_TOKEN.match(old_guid) and old_guid != new_guid:
		mapping.setdefault(old_guid, new_guid)


def pair_materials(embedded_text, sidecar_text, mapping):
	old_ids = primitive_materials(embedded_text)
	new_ids = primitive_materials(sidecar_text)
	if len(old_ids) != len(new_ids):
		return
	for old_id, new_id in zip(old_ids, new_ids):
		if GUID_TOKEN.match(old_id) and GUID_TOKEN.match(new_id) and old_id != new_id:
			mapping.setdefault(old_id, new_id)


def migrate_file(path, root_name, mapping, matcher, dry_run):
	text, bom = read_text(path)
	lines = text.splitlines(keepends=True)

	meta_path, guid_line = read_meta(lines)
	if guid_line is not None and meta_path is not None:
		line, newline = split_newline(lines[guid_line])
		new_guid = z1_guid.guid_for(root_name, meta_path)
		rewritten = re.sub(r"^(\s*guid:\s*)\S+", r"\g<1>" + new_guid, line)
		if rewritten != line:
			lines[guid_line] = rewritten + newline

	new_text = "".join(lines)
	if matcher is not None:
		# the meta guid line already holds the new id, so every hit is a reference
		new_text = matcher.sub(lambda match: mapping.get(match.group(0), match.group(0)), new_text)

	if new_text == text:
		return False
	if not dry_run:
		write_text(path, new_text, bom)
	return True


def migrate_bin(path, mapping, matcher, dry_run):
	"""Rewrites the yaml embedded in a .bin asset (meta + primitive material ids)."""
	if matcher is None:
		return False
	text, data = read_bin_sections(path)
	if text is None:
		return False
	new_text = matcher.sub(lambda match: mapping.get(match.group(0), match.group(0)), text)
	if new_text == text:
		return False
	if not dry_run:
		payload = new_text.encode("utf-8")
		header = BINARY_FILE_HEADER.pack(BINARY_FILE_MAGIC, 1, len(payload), len(data))
		path.write_bytes(header + payload + data)
	return True


def find_unresolved(text, known):
	unresolved = set()
	for token in ANY_GUID.findall(text):
		if token not in known:
			unresolved.add(token)
	return unresolved


def main():
	parser = argparse.ArgumentParser(description="Migrate stored guids to deterministic path-derived ids.")
	parser.add_argument("--dry-run", action="store_true", help="Report changes without writing files")
	args = parser.parse_args()

	mapping, derived = build_map()
	if not mapping:
		print("[OK] nothing to migrate")

	matcher = None
	if mapping:
		pattern = "|".join(re.escape(key) for key in sorted(mapping, key=len, reverse=True))
		matcher = re.compile(pattern)

	updated = 0
	for root_name, root_dir in ROOTS:
		if not root_dir.is_dir():
			continue
		for path in sorted(root_dir.rglob("*")):
			if not path.is_file():
				continue
			suffix = path.suffix.lower()
			if suffix == ".bin":
				changed = migrate_bin(path, mapping, matcher, args.dry_run)
			elif suffix in (".yaml", ".py", ".glsl"):
				changed = migrate_file(path, root_name, mapping, matcher, args.dry_run)
			else:
				continue
			if changed:
				updated += 1
				print(f"[{'DRY-RUN' if args.dry_run else 'FIX'}] {path.relative_to(REPO_ROOT)}")

	for path in EXTRA_FILES:
		if not path.is_file():
			continue
		if migrate_file(path, "", mapping, matcher, args.dry_run):
			updated += 1
			print(f"[{'DRY-RUN' if args.dry_run else 'FIX'}] {path.relative_to(REPO_ROOT)}")

	known = set(mapping) | derived
	unresolved = set()
	for root_name, root_dir in ROOTS:
		if not root_dir.is_dir():
			continue
		for path in sorted(root_dir.rglob("*")):
			if not path.is_file():
				continue
			suffix = path.suffix.lower()
			if suffix in (".yaml", ".py", ".glsl"):
				text, _ = read_text(path)
			elif suffix == ".bin":
				text, _ = read_bin_sections(path)
				if text is None:
					continue
			else:
				continue
			unresolved |= find_unresolved(text, known)

	if unresolved:
		print(f"[WARN] {len(unresolved)} reference(s) still point at unknown ids, e.g. {sorted(unresolved)[:3]}")

	print(f"[OK] {'would update' if args.dry_run else 'updated'} {updated} file(s)")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
