# [AI-GENERATED] This file was generated by an AI agent.

"""Deterministic 128-bit asset ids, mirroring z1::Guid (engine/runtime/source/core/guid.h).

Engine-root assets keep a zero first 32-bit word; other roots hash root + "/" + path and
flip that word if it would be zero, so the two id spaces stay disjoint. Keys are hashed as
the engine sees them: ACP bytes on Windows, UTF-8 elsewhere.
"""

import sys

ENGINE_ROOT = "engine"
FNV_OFFSET_BASIS = 0xCBF29CE484222325
FNV_PRIME = 0x00000100000001B3
MASK64 = 0xFFFFFFFFFFFFFFFF
HEX_LENGTH = 32
FOREIGN_PREFIX_FLIP = 0x80000000


def encode_key(text):
	# mirrors the narrow std::string the engine hashes on Windows (ACP)
	if sys.platform == "win32":
		return text.encode("mbcs", errors="replace")
	return text.encode("utf-8")


def fnv1a64(text):
	hash_value = FNV_OFFSET_BASIS
	for byte in encode_key(text):
		hash_value ^= byte
		hash_value = (hash_value * FNV_PRIME) & MASK64
	return hash_value


def derive_hash(key):
	# domain-separated pair of FNV-1a-64 passes, matching Guid::derive_hash
	return fnv1a64("z1a:" + key), fnv1a64("z1b:" + key)


def guid_from_hash(high, low, engine_asset):
	words = [high >> 32, high & 0xFFFFFFFF, low >> 32, low & 0xFFFFFFFF]
	if engine_asset:
		words[0] = 0
	elif words[0] == 0:
		words[0] = FOREIGN_PREFIX_FLIP
	return "".join(f"{word:08x}" for word in words)


def guid_for(root, path):
	if root == ENGINE_ROOT:
		high, low = derive_hash(path)
		return guid_from_hash(high, low, True)
	high, low = derive_hash(root + "/" + path)
	return guid_from_hash(high, low, False)


def parse_guid(text):
	cleaned = text.replace("-", "")
	if len(cleaned) != HEX_LENGTH:
		return None
	try:
		value = int(cleaned, 16)
	except ValueError:
		return None
	return tuple((value >> shift) & 0xFFFFFFFF for shift in (96, 64, 32, 0))


def format_guid(words):
	return "".join(f"{word & 0xFFFFFFFF:08x}" for word in words)


# Shared with engine/test/test_guid.cpp so the two implementations cannot drift
FNV_VECTORS = [
	("", 0xCBF29CE484222325),
	("a", 0xAF63DC4C8601EC8C),
	("foobar", 0x85944171F73967E8),
]

GUID_VECTORS = [
	("engine", "mesh/SM_Cube", "000000009a9d0329a8631e5aa760403e"),
	("engine", "texture/T_white", "0000000053bd4dbb9fec70d82f7065ae"),
	("", "MI_HappyFace", "7c0104ee0d53c15665831faa784b0ff3"),
	("", "mesh/SM_Cube", "b05388edd50aecc6b92a33f88dcba71f"),
]

HASH_RULE_VECTORS = [
	# (high, low, engine_asset, expected first 8 hex digits)
	(0x0, 0x1234, True, "00000000"),
	(0x0, 0x1234, False, "80000000"),
	(0xDEADBEEF00000000, 0x1234, True, "00000000"),
	(0xDEADBEEF00000000, 0x1234, False, "deadbeef"),
]


def self_test():
	failures = 0
	for text, expected in FNV_VECTORS:
		if fnv1a64(text) != expected:
			print(f"[FAIL] fnv1a64({text!r}) = {fnv1a64(text):016x}, expected {expected:016x}")
			failures += 1
	for root, path, expected in GUID_VECTORS:
		if expected and guid_for(root, path) != expected:
			print(f"[FAIL] guid_for({root!r}, {path!r}) = {guid_for(root, path)}, expected {expected}")
			failures += 1
	for high, low, engine_asset, expected in HASH_RULE_VECTORS:
		actual = guid_from_hash(high, low, engine_asset)[:8]
		if actual != expected:
			print(f"[FAIL] prefix rule ({high:016x}, {low:016x}, engine={engine_asset}) = {actual}, expected {expected}")
			failures += 1
	return failures


if __name__ == "__main__":
	if len(sys.argv) > 1 and sys.argv[1] == "--self-test":
		raise SystemExit(1 if self_test() else 0)
	for root, path, _ in GUID_VECTORS:
		print(f'("{root}", "{path}", "{guid_for(root, path)}"),')
	for text, _ in FNV_VECTORS:
		print(f'("{text}", 0x{fnv1a64(text):016x}ULL),')
