# This file is automatically generated by utils/gen_pybinds.py
# Do not modify this file directly.
from typing import Any, overload, ClassVar, List, Optional
from enum import Enum

def log_info(msg: str) -> None: ...
def log_warn(msg: str) -> None: ...
def log_error(msg: str) -> None: ...
def log_info(*args: Any, **kwargs: Any) -> Any: ...
def log_warn(*args: Any, **kwargs: Any) -> Any: ...
def log_error(*args: Any, **kwargs: Any) -> Any: ...
def hide_cursor(*args: Any, **kwargs: Any) -> Any: ...
def show_cursor(*args: Any, **kwargs: Any) -> Any: ...
def center_cursor(*args: Any, **kwargs: Any) -> Any: ...
def is_cursor_hidden(*args: Any, **kwargs: Any) -> Any: ...
def register_event_listener(type: EventType, callback: Any) -> None: ...

class Event:
	def get_event_type(self, *args: Any, **kwargs: Any) -> Any: ...
	def get_name(self, *args: Any, **kwargs: Any) -> Any: ...
	def __repr__(self) -> str: ...

class KeyEvent:
	key_code: Any

class KeyPressedEvent:
	repeat_count: Any

class KeyReleasedEvent:
	pass

class KeyTypedEvent:
	key_code: Any

class MouseButtonEvent:
	mouse_button: Any

class MouseButtonPressedEvent:
	pass

class MouseButtonReleasedEvent:
	pass

class MouseMovedEvent:
	x: Any
	y: Any

class MouseScrollEvent:
	x_offset: Any
	y_offset: Any

class WindowResizeEvent:
	width: Any
	height: Any

class WindowCloseEvent:
	pass

class Vec2:
	x: float
	y: float
	@overload
	def __init__(self, arg0: float, arg1: float) -> None: ...
	@overload
	def __init__(self) -> None: ...
	def __repr__(self) -> str: ...

class Vec3:
	x: float
	y: float
	z: float
	@overload
	def __init__(self, arg0: float, arg1: float, arg2: float) -> None: ...
	@overload
	def __init__(self) -> None: ...
	def __repr__(self) -> str: ...

class Vec4:
	x: float
	y: float
	z: float
	w: float
	@overload
	def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
	@overload
	def __init__(self) -> None: ...
	def __repr__(self) -> str: ...

class Entity:
	def is_valid(self) -> bool: ...
	def add_static_mesh(self, path: str) -> None: ...
	def add_skeletal_mesh(self, path: str) -> None: ...
	def add_camera(self) -> None: ...
	def add_collider(self, *args: Any, **kwargs: Any) -> Any: ...
	def add_physics(self, *args: Any, **kwargs: Any) -> Any: ...
	def add_script(self, module: str, cls: str) -> None: ...
	@property
	def animation(self) -> Optional[Animation]: ...
	@property
	def camera(self) -> Optional[Camera]: ...
	@property
	def collider(self) -> Optional[Collider]: ...
	@property
	def light(self) -> Optional[Light]: ...
	@property
	def particle(self) -> Optional[Particle]: ...
	@property
	def physics(self) -> Optional[Physics]: ...
	@property
	def postprocess_volume(self) -> Optional[PostprocessVolume]: ...
	@property
	def script(self) -> Optional[Script]: ...
	@property
	def skeletal_mesh(self) -> Optional[SkeletalMesh]: ...
	@property
	def sky_light(self) -> Optional[SkyLight]: ...
	@property
	def sprite(self) -> Optional[Sprite]: ...
	@property
	def static_mesh(self) -> Optional[StaticMesh]: ...
	@property
	def tag(self) -> Optional[Tag]: ...
	@property
	def transform(self) -> Optional[Transform]: ...

class Script:
	@overload
	def __init__(self) -> None: ...
	def on_attach(self) -> None: ...
	def on_start(self) -> None: ...
	def on_update(self, delta: float) -> None: ...
	def on_destroy(self) -> None: ...
	def on_detach(self) -> None: ...
	@property
	def entity(self) -> Optional[Entity]: ...

class Scene:
	@overload
	def __init__(self) -> None: ...
	def create_entity(self, name: str) -> Entity: ...
	def destroy_entity(self, entity: Entity) -> None: ...

# --- GENERATED CONTENT BELOW ---
class EventType(Enum):
	WindowClose = 0
	WindowResize = 1
	WindowFocus = 2
	WindowLostFocus = 3
	WindowMoved = 4
	KeyPressed = 5
	KeyReleased = 6
	KeyTyped = 7
	MouseButtonPressed = 8
	MouseButtonReleased = 9
	MouseMoved = 10
	MouseScrolled = 11

class AOMode(Enum):
	SSAO = 0
	GTAO = 1

class ColliderShape(Enum):
	Sphere = 0
	Box = 1
	Capsule = 2

class DataType(Enum):
	None = 0
	Float = 1
	Float2 = 2
	Float3 = 3
	Float4 = 4
	Int = 5
	Int2 = 6
	Int3 = 7
	Int4 = 8
	Mat3 = 9
	Mat4 = 10
	Bool = 11
	Sampler2D = 12
	Sampler2DArray = 13
	SamplerCube = 14

class EmitterShape(Enum):
	Point = 0
	Sphere = 1
	Box = 2
	Cone = 3

class LightType(Enum):
	Directional = 0
	Point = 1
	Spot = 2

class ParticleBlendMode(Enum):
	Alpha = 0
	Additive = 1
	Soft = 2

class PhysicsMode(Enum):
	Static = 0
	Kinematic = 1
	Dynamic = 2

class RenderMode(Enum):
	Forward = 0
	Deferred = 1

class Animation:
	animation_asset: Optional[Any]
	current_time: float
	speed: float
	loop: bool
	playing: bool

class Camera:
	is_perspective: bool
	near: float
	far: float
	aspect: Any
	use_fixed_aspect: bool
	is_primary: bool
	def __init__(self) -> None: ...

class Collider:
	shape: ColliderShape
	half_extents: Vec3
	def __init__(self) -> None: ...

class GlobalSettings:
	sun_direction: Vec3
	sun_color: Vec4
	sun_intensity: float
	sun_ambient_color: Vec4
	sun_ambient_intensity: float
	taa_enabled: bool
	taa_blend: float
	taa_variance_scale: float
	taa_clip_gamma: float
	taa_sharpen_enabled: bool
	taa_sharpen_strength: float
	taa_animated: bool
	pp_exposure: float
	pp_gamma: float
	pp_tint: Vec4
	pp_bloom_enabled: bool
	pp_bloom_threshold: float
	pp_bloom_intensity: float
	pp_bloom_knee: float
	sm_near: float
	sm_far: float
	sm_ortho_size: float
	ao_enabled: bool
	ao_type: AOMode
	ao_radius: float
	ao_intensity: float
	ao_power: float
	ao_bias: float
	ao_blur_enabled: bool
	ao_blur_strength: float
	anim_enabled: bool
	script_enabled: bool
	render_mode: RenderMode
	def __init__(self) -> None: ...

class Light:
	type: LightType
	color: Vec3
	intensity: float
	range: float
	inner_cone: float
	outer_cone: float
	cast_shadow: bool
	def __init__(self) -> None: ...

class Material:
	flags: int
	shader_guid: Any
	variables: Any

class MaterialInstance:
	material: Optional[Any]
	override_variables: Any
	override_flags: int
	override_mask: int

class Particle:
	max_particles: int
	emission_rate: float
	burst_count: int
	lifetime: Vec2
	initial_speed: Vec2
	direction: Vec3
	direction_spread: float
	gravity: Vec3
	damping: float
	initial_size: Vec2
	size_over_life: Vec2
	initial_color: Vec4
	end_color: Vec4
	texture: Optional[Any]
	blend_mode: ParticleBlendMode
	emitter_shape: EmitterShape
	shape_radius: float
	shape_extents: Vec3
	world_space: bool
	loop: bool
	playing: bool
	sort_by_depth: bool
	receive_shadows: bool
	cast_shadows: bool
	initial_rotation: Vec2
	rotation_speed: Vec2
	def __init__(self) -> None: ...

class Physics:
	mode: PhysicsMode
	mass: float
	use_gravity: bool
	linear_damping: float
	def __init__(self) -> None: ...

class PostprocessVolume:
	enabled: bool
	is_global: bool
	priority: float
	blend_distance: float
	override_exposure: bool
	exposure: float
	override_gamma: bool
	gamma: float
	override_tint: bool
	tint: Vec4
	override_bloom_enabled: bool
	bloom_enabled: bool
	override_bloom_threshold: bool
	bloom_threshold: float
	override_bloom_intensity: bool
	bloom_intensity: float
	override_bloom_knee: bool
	bloom_knee: float

class Script:
	def __init__(self) -> None: ...

class SkeletalMesh:
	mesh: Optional[Any]
	skeleton: Optional[Any]
	override_materials: Optional[Any]

class SkyLight:
	texture: Optional[Any]
	rotation: float
	intensity: float
	mip_level: float
	def __init__(self) -> None: ...

class Sprite:
	color: Vec4
	texture: Optional[Any]
	tiling_scale: Vec2
	tiling_offset: Vec2
	texcoords: List[Vec2]
	extras: List[Vec2]
	def __init__(self) -> None: ...

class StaticMesh:
	mesh: Optional[Any]
	override_materials: Optional[Any]

class Tag:
	tag: str
	id: int
	def __init__(self) -> None: ...

class Transform:
	location: Vec3
	rotation: Vec3
	scale: Vec3
	def __init__(self) -> None: ...

globals: GlobalSettings
scene: Scene
