# This file is automatically generated by utils/gen_pybinds.py
# Do not modify this file directly.
from typing import Any, overload, ClassVar, List, Optional
from enum import Enum

def log_info(msg: str) -> None: ...
def log_warn(msg: str) -> None: ...
def log_error(msg: str) -> None: ...

class Vec2:
	x: float
	y: float
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, x: float, y: float) -> None: ...
	def __repr__(self) -> str: ...

class Vec3:
	x: float
	y: float
	z: float
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, x: float, y: float, z: float) -> None: ...
	def __repr__(self) -> str: ...

class Vec4:
	x: float
	y: float
	z: float
	w: float
	@overload
	def __init__(self) -> None: ...
	@overload
	def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
	def __repr__(self) -> str: ...

class Animation:
	animation_asset: Any
	current_time: float
	speed: float
	loop: bool
	playing: bool

class Camera:
	is_perspective: bool
	near: float
	far: float
	aspect: Any
	use_fixed_aspect: bool
	is_primary: bool
	def __init__(self) -> None: ...

class GlobalSettings:
	sun_direction: Vec3
	sun_color: Vec4
	sun_intensity: float
	sun_ambient_color: Vec4
	sun_ambient_intensity: float
	taa_enabled: bool
	taa_blend: float
	taa_animated: bool
	pp_exposure: float
	pp_gamma: float
	pp_tint: Vec4
	pp_bloom_enabled: bool
	pp_bloom_threshold: float
	pp_bloom_intensity: float
	pp_bloom_knee: float
	sm_near: float
	sm_far: float
	sm_ortho_size: float
	anim_enabled: bool
	def __init__(self) -> None: ...

class Light:
	type: int
	color: Vec3
	intensity: float
	range: float
	inner_cone: float
	outer_cone: float
	cast_shadow: bool
	def __init__(self) -> None: ...

class SkeletalMesh:
	pass

class SkyLight:
	texture: Any
	rotation: float
	intensity: float
	mip_level: float
	def __init__(self) -> None: ...

class Sprite:
	color: Vec4
	texture: Any
	tiling_scale: Vec2
	tiling_offset: Vec2
	texcoords: Vec2
	extras: Vec2
	def __init__(self) -> None: ...

class StaticMesh:
	pass

class Tag:
	tag: str
	def __init__(self) -> None: ...

class Transform:
	location: Vec3
	rotation: Vec3
	scale: Vec3
	def __init__(self) -> None: ...

class Entity:
	@property
	def animation(self) -> Optional[Animation]: ...
	@property
	def camera(self) -> Optional[Camera]: ...
	@property
	def light(self) -> Optional[Light]: ...
	@property
	def skeletal_mesh(self) -> Optional[SkeletalMesh]: ...
	@property
	def sky_light(self) -> Optional[SkyLight]: ...
	@property
	def sprite(self) -> Optional[Sprite]: ...
	@property
	def static_mesh(self) -> Optional[StaticMesh]: ...
	@property
	def tag(self) -> Optional[Tag]: ...
	@property
	def transform(self) -> Optional[Transform]: ...
	def is_valid(self) -> bool: ...

class Script:
	def __init__(self) -> None: ...
	def on_attach(self) -> None: ...
	def on_update(self, delta_time: float) -> None: ...
	def on_detach(self) -> None: ...
	@property
	def entity(self) -> Optional[Entity]: ...
