# This file is automatically generated by utils/gen_pybinds.py
# Do not modify this file directly.
from typing import Any, overload, ClassVar, List, Optional
from enum import Enum

def log_info(msg: str) -> None: ...
def log_warn(msg: str) -> None: ...
def log_error(msg: str) -> None: ...
def log_info(*args: Any, **kwargs: Any) -> Any: ...
def log_warn(*args: Any, **kwargs: Any) -> Any: ...
def register_event_listener(type: EventType, callback: Any) -> None: ...

class Event:
	def get_event_type(self, *args: Any, **kwargs: Any) -> Any: ...
	def get_name(self, *args: Any, **kwargs: Any) -> Any: ...
	def __repr__(self) -> str: ...

class KeyEvent:
	key_code: Any

class KeyPressedEvent:
	repeat_count: Any

class KeyReleasedEvent:
	pass

class KeyTypedEvent:
	key_code: Any

class MouseButtonEvent:
	mouse_button: Any

class MouseButtonPressedEvent:
	pass

class MouseButtonReleasedEvent:
	pass

class MouseMovedEvent:
	x: Any
	y: Any

class MouseScrollEvent:
	x_offset: Any
	y_offset: Any

class WindowResizeEvent:
	width: Any
	height: Any

class WindowCloseEvent:
	pass

class Vec2:
	x: float
	y: float
	@overload
	def __init__(self, arg0: float, arg1: float) -> None: ...
	@overload
	def __init__(self) -> None: ...
	def __repr__(self) -> str: ...

class Vec3:
	x: float
	y: float
	z: float
	@overload
	def __init__(self, arg0: float, arg1: float, arg2: float) -> None: ...
	@overload
	def __init__(self) -> None: ...
	def __repr__(self) -> str: ...

class Vec4:
	x: float
	y: float
	z: float
	w: float
	@overload
	def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None: ...
	@overload
	def __init__(self) -> None: ...
	def __repr__(self) -> str: ...

class Entity:
	def is_valid(self) -> bool: ...
	def add_static_mesh(self, path: str) -> None: ...
	def add_skeletal_mesh(self, path: str) -> None: ...
	def add_camera(self) -> None: ...
	def add_script(self, module: str, cls: str) -> None: ...
	@property
	def animation(self) -> Optional[Animation]: ...
	@property
	def camera(self) -> Optional[Camera]: ...
	@property
	def light(self) -> Optional[Light]: ...
	@property
	def skeletal_mesh(self) -> Optional[SkeletalMesh]: ...
	@property
	def sky_light(self) -> Optional[SkyLight]: ...
	@property
	def sprite(self) -> Optional[Sprite]: ...
	@property
	def static_mesh(self) -> Optional[StaticMesh]: ...
	@property
	def tag(self) -> Optional[Tag]: ...
	@property
	def transform(self) -> Optional[Transform]: ...

class Script:
	@overload
	def __init__(self) -> None: ...
	def on_attach(self) -> None: ...
	def on_start(self) -> None: ...
	def on_update(self, delta: float) -> None: ...
	def on_destroy(self) -> None: ...
	def on_detach(self) -> None: ...
	@property
	def entity(self) -> Optional[Entity]: ...

class Scene:
	@overload
	def __init__(self) -> None: ...
	def create_entity(self, name: str) -> Entity: ...
	def destroy_entity(self, entity: Entity) -> None: ...

# --- GENERATED CONTENT BELOW ---
class EventType(Enum):
	WindowClose = 0
	WindowResize = 1
	WindowFocus = 2
	WindowLostFocus = 3
	WindowMoved = 4
	KeyPressed = 5
	KeyReleased = 6
	KeyTyped = 7
	MouseButtonPressed = 8
	MouseButtonReleased = 9
	MouseMoved = 10
	MouseScrolled = 11

class LightType(Enum):
	Directional = 0
	Point = 1
	Spot = 2

class Animation:
	animation_asset: Optional[Any]
	current_time: float
	speed: float
	loop: bool
	playing: bool

class Camera:
	is_perspective: bool
	near: float
	far: float
	aspect: Any
	use_fixed_aspect: bool
	is_primary: bool
	def __init__(self) -> None: ...

class GlobalSettings:
	sun_direction: Vec3
	sun_color: Vec4
	sun_intensity: float
	sun_ambient_color: Vec4
	sun_ambient_intensity: float
	taa_enabled: bool
	taa_blend: float
	taa_animated: bool
	pp_exposure: float
	pp_gamma: float
	pp_tint: Vec4
	pp_bloom_enabled: bool
	pp_bloom_threshold: float
	pp_bloom_intensity: float
	pp_bloom_knee: float
	sm_near: float
	sm_far: float
	sm_ortho_size: float
	anim_enabled: bool
	script_enabled: bool
	def __init__(self) -> None: ...

class Light:
	type: LightType
	color: Vec3
	intensity: float
	range: float
	inner_cone: float
	outer_cone: float
	cast_shadow: bool
	def __init__(self) -> None: ...

class SkeletalMesh:
	pass

class SkyLight:
	texture: Optional[Any]
	rotation: float
	intensity: float
	mip_level: float
	def __init__(self) -> None: ...

class Sprite:
	color: Vec4
	texture: Optional[Any]
	tiling_scale: Vec2
	tiling_offset: Vec2
	texcoords: List[Vec2]
	extras: List[Vec2]
	def __init__(self) -> None: ...

class StaticMesh:
	pass

class Tag:
	tag: str
	def __init__(self) -> None: ...

class Transform:
	location: Vec3
	rotation: Vec3
	scale: Vec3
	def __init__(self) -> None: ...

globals: GlobalSettings
scene: Scene
